var searchData=
[
  ['b_201_20core_20models_20models_20py_0',['B.1 CORE MODELS (models.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md102',1,'']]],
  ['b_202_20the_20scheduling_20algorithm_20scheduler_20py_1',['B.2 THE SCHEDULING ALGORITHM (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'']]],
  ['b_203_20the_20controller_20routes_20py_20logic_20excerpts_2',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['b_20teachers_20teachers_20csv_3',['B. TEACHERS (teachers.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md83',1,'']]],
  ['b_3a_20database_20schema_20sql_4',['Appendix B: Database Schema SQL',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md480',1,'']]],
  ['backend_20technologies_5',['5.1 Backend Technologies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md210',1,'']]],
  ['background_20engine_6',['7.3 DYNAMIC CANVAS ANIMATIONS (Background Engine)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['background_20not_20animating_7',['Issue: Particle background not animating',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md382',1,'']]],
  ['backup_8',['16.3 RESTORING FROM BACKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md162',1,'']]],
  ['backup_9',['Database Backup',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md388',1,'']]],
  ['backup_20and_20recovery_10',['21.3 Backup and Recovery',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md387',1,'']]],
  ['backup_20policy_11',['G.2 DATABASE BACKUP POLICY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md133',1,'']]],
  ['badge_12',['15.4 Navigation Badge',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md318',1,'']]],
  ['base_20html_13',['base html',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md293',1,'12.2 Master Layout (base.html)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md141',1,'J.1 THE MASTER LAYOUT (templates/base.html)']]],
  ['based_20access_20control_14',['Role-Based Access Control',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md431',1,'']]],
  ['based_20access_20control_20rbac_15',['Based Access Control RBAC',['../md__r_e_a_d_m_e.html#autotoc_md171',1,'👥 Role-Based Access Control (RBAC)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md282',1,'11. Role-Based Access Control (RBAC)']]],
  ['based_20navigation_3a_16',['Role-based navigation:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md353',1,'']]],
  ['based_20permission_20matrix_17',['K.1 ROLE-BASED PERMISSION MATRIX',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md143',1,'']]],
  ['batch_20limit_20reached_18',['Issue: &quot;Department batch limit reached&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md376',1,'']]],
  ['best_20practices_19',['Best Practices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md439',1,'24.5 Security Best Practices'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md476',1,'27.5 Security and Best Practices']]],
  ['big_20o_20notation_20',['13.3 COMPLEXITY ANALYSIS (Big-O Notation)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md140',1,'']]],
  ['blank_20or_20corrupted_21',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['block_22',['Transactional Block',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md118',1,'']]],
  ['blocks_203_20hour_20rule_23',['5.3 HANDLING PRACTICAL/LAB BLOCKS (3-Hour Rule)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['blueprint_20definition_24',['9.2 Blueprint Definition',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md254',1,'']]],
  ['blueprint_20organization_25',['3.3 BLUEPRINT ORGANIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'']]],
  ['blueprint_20registration_26',['8.3.5 Blueprint Registration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md249',1,'']]],
  ['break_20protection_27',['H.1 LUNCH BREAK PROTECTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md135',1,'']]],
  ['breakdown_28',['2.2 FUNCTIONAL REQUIREMENTS BREAKDOWN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['bridge_20table_29',['4.2.5 TABLE: allocation (The Bridge Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['bug_20log_20and_20resolution_30',['10.4 BUG LOG AND RESOLUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md93',1,'']]],
  ['build_20optional_31',['17.4 Desktop Application Build (Optional)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md337',1,'']]],
  ['building_32',['Step 3: DOMAIN BUILDING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md272',1,'']]],
  ['bulk_20data_20upload_20csv_33',['15.3.3 BULK DATA UPLOAD (CSV)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md157',1,'']]],
  ['bulk_20import_20feature_34',['13. CSV Bulk Import Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md302',1,'']]],
  ['bulk_20input_20parsing_20logic_35',['8.1 THE BULK INPUT PARSING LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['bulk_20operations_36',['Bulk Operations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md399',1,'']]],
  ['by_20duration_20descending_37',['Priority Hack: Sort by duration descending',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md110',1,'']]]
];
