var searchData=
[
  ['e_201_20the_20design_20tokens_20index_20css_0',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['e_202_20animation_20engine_20main_20js_1',['E.2 ANIMATION ENGINE (main.js)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md125',1,'']]],
  ['e_20g_20only_201_20room_20for_2010_20classes_2',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['each_20candidate_20slot_3',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['edit_20routes_4',['Edit Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md261',1,'']]],
  ['edit_20timetable_20entry_5',['20.4 Edit Timetable Entry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md365',1,'']]],
  ['edit_20timetable_20entry_20edit_5ftimetable_5fentry_20html_6',['EDIT TIMETABLE ENTRY (edit_timetable_entry.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md298',1,'']]],
  ['edit_5ftimetable_5fentry_20html_7',['EDIT TIMETABLE ENTRY (edit_timetable_entry.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md298',1,'']]],
  ['edits_20and_20fine_20tuning_8',['15.5 MANUAL EDITS AND FINE-TUNING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md159',1,'']]],
  ['educational_20value_9',['Educational Value',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md468',1,'']]],
  ['engine_10',['7.3 DYNAMIC CANVAS ANIMATIONS (Background Engine)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['engine_20main_20js_11',['E.2 ANIMATION ENGINE (main.js)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md125',1,'']]],
  ['engine_20scheduler_20py_12',['10. Intelligent Scheduling Engine (scheduler.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md267',1,'']]],
  ['enhanced_20scheduling_13',['AI-Enhanced Scheduling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md455',1,'']]],
  ['enhancements_14',['25. Future Enhancements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md444',1,'']]],
  ['enhancements_20v1_201_15',['25.1 Short-Term Enhancements (v1.1)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md445',1,'']]],
  ['enhancements_20v2_200_16',['25.2 Medium-Term Enhancements (v2.0)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md449',1,'']]],
  ['ensure_20that_20if_20a_20department_20is_20removed_17',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['enterprise_20features_18',['Enterprise Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md458',1,'Enterprise Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md462',1,'Phase 3 (12 months): Enterprise Features']]],
  ['entity_20relationship_20diagram_19',['7.2 Entity Relationship Diagram',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md228',1,'']]],
  ['entry_20',['20.4 Edit Timetable Entry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md365',1,'']]],
  ['entry_20edit_5ftimetable_5fentry_20html_21',['EDIT TIMETABLE ENTRY (edit_timetable_entry.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md298',1,'']]],
  ['entry_20form_22',['Timetable Entry Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md407',1,'']]],
  ['entry_20point_20app_20py_23',['6.1 APPLICATION ENTRY POINT (app.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['entry_20point_20app_20py_24',['8. Application Entry Point (app.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md241',1,'']]],
  ['environment_20recommended_25',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['er_20diagram_20overview_26',['4.1 ER DIAGRAM OVERVIEW',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md19',1,'']]],
  ['error_20codes_27',['G.1 COMMON ERROR CODES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md132',1,'']]],
  ['error_20handlers_28',['8.3.4 Error Handlers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md248',1,'']]],
  ['error_20handling_29',['Error Handling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md441',1,'']]],
  ['error_20handling_20in_20csv_20imports_30',['8.3 ERROR HANDLING IN CSV IMPORTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md86',1,'']]],
  ['errors_31',['Issue: Database locked errors',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md380',1,'']]],
  ['ethics_32',['18.1 INSTITUTIONAL DATA ETHICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md165',1,'']]],
  ['example_33',['Example',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md224',1,'Data Flow Example'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md223',1,'Request Flow Example']]],
  ['examples_34',['Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md347',1,'19.1 Database Query Examples'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md351',1,'19.2 Template Rendering Examples'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md354',1,'19.3 JavaScript Examples'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md357',1,'19.4 Algorithm Logic Examples']]],
  ['examples_20and_20snippets_35',['19. Code Examples and Snippets',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md346',1,'']]],
  ['excellence_36',['Technical Excellence',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md467',1,'']]],
  ['excerpts_37',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['executable_38',['11.2 DESKTOP DEPLOYMENT (THE EXECUTABLE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md95',1,'']]],
  ['existing_20schedule_39',['1. Clear existing schedule',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md107',1,'']]],
  ['experience_40',['15.1 THE LOGIN EXPERIENCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md153',1,'']]],
  ['experience_41',['Experience',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md461',1,'Phase 2 (6 months): User Experience'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md447',1,'User Experience']]],
  ['explained_42',['8.3 Key Sections Explained',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md244',1,'']]],
  ['export_20feature_43',['16. PDF Export Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md321',1,'']]],
  ['export_20is_20blank_20or_20corrupted_44',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['export_20javascript_45',['16.3 PDF Export JavaScript',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md324',1,'']]],
  ['export_20options_46',['16.4 Export Options',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md325',1,'']]],
  ['export_20result_47',['20.8 PDF Export Result',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md369',1,'']]],
  ['extract_20the_20project_20zip_48',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]]
];
