var searchData=
[
  ['a_201_20table_3a_20department_20metadata_0',['A.1 TABLE: DEPARTMENT (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md97',1,'']]],
  ['a_202_20table_3a_20course_20metadata_1',['A.2 TABLE: COURSE (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md98',1,'']]],
  ['a_203_20table_3a_20teacher_20metadata_2',['A.3 TABLE: TEACHER (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md99',1,'']]],
  ['a_204_20table_3a_20classroom_20metadata_3',['A.4 TABLE: CLASSROOM (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md100',1,'']]],
  ['a_205_20table_3a_20timetable_5fentry_20the_20master_20table_4',['A.5 TABLE: TIMETABLE_ENTRY (The Master Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'']]],
  ['a_20department_20is_20removed_5',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['a_20department_3a_6',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['a_20new_20semester_7',['9.1 ADMINISTRATOR GUIDE: SETTING UP A NEW SEMESTER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'']]],
  ['a_20subjects_20courses_20subjects_20csv_8',['A. SUBJECTS/COURSES (subjects.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['a_20virtual_20environment_20recommended_9',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['a_3a_20requirements_20txt_10',['Appendix A: Requirements.txt',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md479',1,'']]],
  ['academic_20and_20research_20papers_11',['27.2 Academic and Research Papers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md473',1,'']]],
  ['academic_20life_12',['9.2 TEACHER GUIDE: MANAGING YOUR ACADEMIC LIFE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md88',1,'']]],
  ['acceptance_20testing_20uat_13',['10.2 USER ACCEPTANCE TESTING (UAT)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md91',1,'']]],
  ['access_20control_14',['Role-Based Access Control',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md431',1,'']]],
  ['access_20control_20implementation_15',['11.3 Access Control Implementation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md285',1,'']]],
  ['access_20control_20rbac_16',['Access Control RBAC',['../md__r_e_a_d_m_e.html#autotoc_md171',1,'👥 Role-Based Access Control (RBAC)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md282',1,'11. Role-Based Access Control (RBAC)']]],
  ['access_20matrix_17',['11.4 Feature Access Matrix',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md289',1,'']]],
  ['access_20the_20application_18',['STEP 5: Access the application',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md334',1,'']]],
  ['achievements_19',['Key Achievements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md466',1,'']]],
  ['activate_20a_20virtual_20environment_20recommended_20',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['activity_20class_20assignment_21',['Step 6: ACTIVITY CLASS ASSIGNMENT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md275',1,'']]],
  ['activity_20class_20assignment_20logic_22',['10.5 Activity Class Assignment Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md279',1,'']]],
  ['activity_20class_20slot_20allocation_20logic_23',['5.4 ACTIVITY CLASS SLOT ALLOCATION LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['admin_20dashboard_24',['7.4.1 THE ADMIN DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md73',1,'']]],
  ['admin_20dashboard_20mockup_25',['F.2 ADMIN DASHBOARD MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md129',1,'']]],
  ['admin_20guard_20decorator_26',['9.3 Admin Guard Decorator',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md255',1,'']]],
  ['admin_20login_27',['STEP 6: First Admin Login',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md335',1,'']]],
  ['administration_20crud_28',['6.2.2 DATA ADMINISTRATION (CRUD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['administrative_20onboarding_29',['15.2 ADMINISTRATIVE ONBOARDING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md154',1,'']]],
  ['administrator_20guide_3a_20setting_20up_20a_20new_20semester_30',['9.1 ADMINISTRATOR GUIDE: SETTING UP A NEW SEMESTER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'']]],
  ['advanced_20features_31',['Advanced Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md453',1,'']]],
  ['advanced_20modules_32',['Advanced Modules',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md457',1,'']]],
  ['after_20install_33',['17.3 Initial Setup Workflow (After Install)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md336',1,'']]],
  ['ahead_34',['14.3 THE JOURNEY AHEAD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md148',1,'']]],
  ['ai_20enhanced_20scheduling_35',['AI-Enhanced Scheduling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md455',1,'']]],
  ['ai_20integration_36',['11.3 FUTURE WORK (AI INTEGRATION)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md96',1,'']]],
  ['ai_20integration_37',['Phase 4 (18 months): AI Integration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md463',1,'']]],
  ['algorithm_20design_38',['10.2 Scheduling Algorithm Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md269',1,'']]],
  ['algorithm_20logic_20examples_39',['19.4 Algorithm Logic Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md357',1,'']]],
  ['algorithm_20returns_20false_20and_20informs_20the_20user_40',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['algorithm_20scheduler_20py_41',['B.2 THE SCHEDULING ALGORITHM (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'']]],
  ['algorithm_20walkthrough_42',['5.5 CONFLICT DETECTION ALGORITHM WALKTHROUGH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['alignment_43',['Global Constants for institutional alignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md103',1,'']]],
  ['all_20courses_20for_20a_20department_3a_44',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['all_20python_20dependencies_45',['STEP 3: Install all Python dependencies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md332',1,'']]],
  ['all_20rights_20reserved_46',['[ ALL RIGHTS RESERVED ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md152',1,'']]],
  ['allocation_47',['Allocation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md234',1,'7.8 Data Model: Allocation'],['../classmodels_1_1_allocation.html',1,'models.Allocation']]],
  ['allocation_20logic_48',['5.4 ACTIVITY CLASS SLOT ALLOCATION LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['allocation_20the_20bridge_20table_49',['4.2.5 TABLE: allocation (The Bridge Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['allocations_20allocations_20csv_50',['C. ALLOCATIONS (allocations.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'']]],
  ['allocations_20csv_51',['C. ALLOCATIONS (allocations.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'']]],
  ['already_20occupied_52',['Issue: &quot;Classroom is already occupied&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md375',1,'']]],
  ['also_20cleaned_20up_53',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['analysis_54',['Analysis',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md426',1,'24. Security Analysis'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md221',1,'6.3 File Structure Analysis']]],
  ['analysis_20big_20o_20notation_55',['13.3 COMPLEXITY ANALYSIS (Big-O Notation)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md140',1,'']]],
  ['and_20activate_20a_20virtual_20environment_20recommended_56',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['and_20best_20practices_57',['27.5 Security and Best Practices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md476',1,'']]],
  ['and_20constraints_58',['4.3 Assumptions and Constraints',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md205',1,'']]],
  ['and_20controller_20logic_20routes_20py_59',['9. Routing and Controller Logic (routes.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'']]],
  ['and_20controllers_20routes_20py_60',['6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['and_20data_20models_61',['7. Database Design and Data Models',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md226',1,'']]],
  ['and_20deployment_20guide_62',['17. Installation and Deployment Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md327',1,'']]],
  ['and_20fine_20tuning_63',['15.5 MANUAL EDITS AND FINE-TUNING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md159',1,'']]],
  ['and_20frameworks_64',['27.1 Documentation and Frameworks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md472',1,'']]],
  ['and_20frontend_20design_65',['12. User Interface and Frontend Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md291',1,'']]],
  ['and_20informs_20the_20user_66',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['and_20main_20views_67',['Dashboard and Main Views',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md394',1,'']]],
  ['and_20migrations_68',['6.3 UTILITY SCRIPTS (Checkers and Migrations)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'']]],
  ['and_20profiling_69',['23.4 Monitoring and Profiling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md422',1,'']]],
  ['and_20recovery_70',['21.3 Backup and Recovery',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md387',1,'']]],
  ['and_20registration_71',['6.2.1 AUTHENTICATION AND REGISTRATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md56',1,'']]],
  ['and_20research_20papers_72',['27.2 Academic and Research Papers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md473',1,'']]],
  ['and_20resolution_73',['10.4 BUG LOG AND RESOLUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md93',1,'']]],
  ['and_20resources_74',['27.3 Development Tools and Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md474',1,'']]],
  ['and_20snippets_75',['19. Code Examples and Snippets',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md346',1,'']]],
  ['and_20software_20prerequisites_76',['2.4 HARDWARE AND SOFTWARE PREREQUISITES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md13',1,'']]],
  ['and_20solutions_77',['21.1 Common Issues and Solutions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md372',1,'']]],
  ['and_20substitution_20controller_78',['6.2.5 LEAVE AND SUBSTITUTION CONTROLLER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md64',1,'']]],
  ['and_20substitution_20system_79',['14. Leave Management and Substitution System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md308',1,'']]],
  ['and_20teacher_20links_20are_20also_20cleaned_20up_80',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['and_20ui_20resources_81',['27.4 Design and UI Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md475',1,'']]],
  ['and_20validate_82',['3. Loop and Validate',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md109',1,'']]],
  ['and_20validation_83',['18. Testing and Validation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md340',1,'']]],
  ['and_20visual_20guide_84',['20. Screenshots and Visual Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md361',1,'']]],
  ['animating_85',['Issue: Particle background not animating',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md382',1,'']]],
  ['animation_86',['12.5 Particle Network Animation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md300',1,'']]],
  ['animation_20engine_20main_20js_87',['E.2 ANIMATION ENGINE (main.js)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md125',1,'']]],
  ['animation_20initialization_3a_88',['Particle animation initialization:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md355',1,'']]],
  ['animations_20background_20engine_89',['7.3 DYNAMIC CANVAS ANIMATIONS (Background Engine)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['api_20development_90',['API Development',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md451',1,'']]],
  ['api_20reference_91',['22. API Reference',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md391',1,'']]],
  ['app_20py_92',['app py',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'6.1 APPLICATION ENTRY POINT (app.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md241',1,'8. Application Entry Point (app.py)']]],
  ['app_20py_3a_93',['KEY COMPONENTS OF app.py:',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['appendices_94',['28. Appendices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md478',1,'']]],
  ['appendix_20a_3a_20requirements_20txt_95',['Appendix A: Requirements.txt',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md479',1,'']]],
  ['appendix_20b_3a_20database_20schema_20sql_96',['Appendix B: Database Schema SQL',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md480',1,'']]],
  ['appendix_20c_3a_20pyinstaller_20spec_20file_97',['Appendix C: PyInstaller Spec File',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md481',1,'']]],
  ['appendix_20d_3a_20sample_20data_20for_20testing_98',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['application_99',['STEP 5: Access the application',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md334',1,'']]],
  ['application_20build_20optional_100',['17.4 Desktop Application Build (Optional)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md337',1,'']]],
  ['application_20entry_20point_20app_20py_101',['6.1 APPLICATION ENTRY POINT (app.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['application_20entry_20point_20app_20py_102',['8. Application Entry Point (app.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md241',1,'']]],
  ['application_20performance_103',['23.2 Application Performance',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md414',1,'']]],
  ['application_20won_20t_20start_104',['Issue: Application won&apos;t start',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md379',1,'']]],
  ['approach_105',['1.3 PROPOSED SOLUTION: THE INTELLIGENT APPROACH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['architectural_20pattern_106',['6.1 Architectural Pattern',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md219',1,'']]],
  ['architecture_107',['3.1 HIGH-LEVEL SYSTEM ARCHITECTURE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md15',1,'']]],
  ['architecture_108',['6. System Architecture',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md218',1,'']]],
  ['architecture_20diagram_109',['6.2 Architecture Diagram',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md220',1,'']]],
  ['are_20also_20cleaned_20up_110',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['assessment_111',['1.5 IMPACT ASSESSMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['assignment_112',['Step 6: ACTIVITY CLASS ASSIGNMENT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md275',1,'']]],
  ['assignment_113',['Record successful assignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md114',1,'']]],
  ['assignment_20logic_114',['10.5 Activity Class Assignment Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md279',1,'']]],
  ['assumptions_115',['Assumptions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md206',1,'']]],
  ['assumptions_20and_20constraints_116',['4.3 Assumptions and Constraints',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md205',1,'']]],
  ['attending_20classes_117',['9.3 STUDENT GUIDE: ATTENDING CLASSES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md89',1,'']]],
  ['audit_20logging_118',['Audit Logging',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md442',1,'']]],
  ['audit_20logs_119',['16.2 INTERNAL AUDIT LOGS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md161',1,'']]],
  ['authentication_20and_20registration_120',['6.2.1 AUTHENTICATION AND REGISTRATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md56',1,'']]],
  ['authentication_20routes_121',['Authentication Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md256',1,'9.4 Authentication Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md393',1,'Authentication Routes']]],
  ['authentication_20security_122',['24.1 Authentication Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md427',1,'']]],
  ['authentication_20tests_123',['C.1 AUTHENTICATION TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md120',1,'']]],
  ['authorization_20security_124',['24.2 Authorization Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md430',1,'']]],
  ['availability_3a_125',['Check teacher availability:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md350',1,'']]],
  ['aws_20azure_126',['11.1 CLOUD DEPLOYMENT (HEROKU / AWS / AZURE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md94',1,'']]],
  ['azure_127',['11.1 CLOUD DEPLOYMENT (HEROKU / AWS / AZURE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md94',1,'']]]
];
