var searchData=
[
  ['page_0',['20.1 Login Page',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md362',1,'']]],
  ['page_20login_20html_1',['LOGIN PAGE (login.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md295',1,'']]],
  ['page_20mockup_2',['F.1 LOGIN PAGE MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md127',1,'']]],
  ['page_20timetable_20html_3',['TIMETABLE PAGE (timetable.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md297',1,'']]],
  ['pages_4',['12.3 Key Pages',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md294',1,'']]],
  ['papers_5',['27.2 Academic and Research Papers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md473',1,'']]],
  ['parameters_6',['22.3 Form Data Parameters',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md401',1,'']]],
  ['parsing_20logic_7',['8.1 THE BULK INPUT PARSING LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['particle_20animation_20initialization_3a_8',['Particle animation initialization:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md355',1,'']]],
  ['particle_20background_20not_20animating_9',['Issue: Particle background not animating',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md382',1,'']]],
  ['particle_20network_20animation_10',['12.5 Particle Network Animation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md300',1,'']]],
  ['password_11',['Issue: &quot;Invalid username or password&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md374',1,'']]],
  ['password_20storage_12',['Password Storage',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md428',1,'']]],
  ['pattern_13',['3.2 THE MODEL-VIEW-CONTROLLER (MVC) PATTERN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['pattern_14',['6.1 Architectural Pattern',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md219',1,'']]],
  ['pdf_20export_20feature_15',['16. PDF Export Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md321',1,'']]],
  ['pdf_20export_20is_20blank_20or_20corrupted_16',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['pdf_20export_20javascript_17',['16.3 PDF Export JavaScript',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md324',1,'']]],
  ['pdf_20export_20result_18',['20.8 PDF Export Result',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md369',1,'']]],
  ['penetration_20testing_19',['10.3 SECURITY PENETRATION TESTING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md92',1,'']]],
  ['performance_20',['Performance',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md410',1,'23.1 Database Performance'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md414',1,'23.2 Application Performance'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md385',1,'Frontend Performance'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md448',1,'Performance']]],
  ['performance_20considerations_21',['23. Performance Considerations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md409',1,'']]],
  ['performance_20monitoring_22',['Performance Monitoring',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md423',1,'']]],
  ['performance_20optimization_23',['21.2 Performance Optimization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md383',1,'']]],
  ['permission_20matrix_24',['K.1 ROLE-BASED PERMISSION MATRIX',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md143',1,'']]],
  ['persona_20dashboards_25',['7.4 USER PERSONA DASHBOARDS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md71',1,'']]],
  ['phase_201_203_20months_20_3a_20security_20stability_26',['Phase 1 (3 months): Security &amp;amp; Stability',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md460',1,'']]],
  ['phase_202_206_20months_20_3a_20user_20experience_27',['Phase 2 (6 months): User Experience',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md461',1,'']]],
  ['phase_203_2012_20months_20_3a_20enterprise_20features_28',['Phase 3 (12 months): Enterprise Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md462',1,'']]],
  ['phase_204_2018_20months_20_3a_20ai_20integration_29',['Phase 4 (18 months): AI Integration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md463',1,'']]],
  ['philosophy_30',['12.1 Design Philosophy',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md292',1,'']]],
  ['place_20in_20room_31',['Place in Room...',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md113',1,'']]],
  ['point_20app_20py_32',['6.1 APPLICATION ENTRY POINT (app.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'']]],
  ['point_20app_20py_33',['8. Application Entry Point (app.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md241',1,'']]],
  ['policy_34',['G.2 DATABASE BACKUP POLICY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md133',1,'']]],
  ['potential_35',['Future Potential',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md469',1,'']]],
  ['practical_20lab_20blocks_203_20hour_20rule_36',['5.3 HANDLING PRACTICAL/LAB BLOCKS (3-Hour Rule)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['practical_20session_20logistics_37',['H.3 PRACTICAL SESSION LOGISTICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md137',1,'']]],
  ['practical_20sessions_203_20hour_20slots_38',['Logic for Practical sessions (3-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['practicals_20first_39',['2. Sort requirements (Practicals first)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md108',1,'']]],
  ['practices_40',['Practices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md439',1,'24.5 Security Best Practices'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md476',1,'27.5 Security and Best Practices']]],
  ['preface_41',['1.1 PREFACE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md5',1,'']]],
  ['prerequisites_42',['2.4 HARDWARE AND SOFTWARE PREREQUISITES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md13',1,'']]],
  ['prerequisites_43',['Prerequisites',['../md__r_e_a_d_m_e.html#autotoc_md175',1,'📝 Prerequisites'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md328',1,'17.1 Prerequisites']]],
  ['preventing_20database_20overlaps_44',['K.3 PREVENTING DATABASE OVERLAPS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md145',1,'']]],
  ['prevents_20repetitive_20schedules_45',['Randomized &apos;Domain&apos; prevents repetitive schedules',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md111',1,'']]],
  ['primary_20objectives_46',['3.1 Primary Objectives',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md196',1,'']]],
  ['prioritization_47',['Step 2: PRIORITIZATION',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md271',1,'']]],
  ['priority_20hack_3a_20sort_20by_20duration_20descending_48',['Priority Hack: Sort by duration descending',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md110',1,'']]],
  ['priority_20scheduling_20heuristics_49',['5.2 PRIORITY SCHEDULING HEURISTICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['privacy_20gdpr_20compliance_50',['18.2 DATA PRIVACY &amp;amp; GDPR COMPLIANCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md166',1,'']]],
  ['problem_20csp_51',['5.1 THE CONSTRAINT-SATISFACTION PROBLEM (CSP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['problem_20csp_20model_52',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['problem_20statement_53',['1.2 THE CORE PROBLEM STATEMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md6',1,'']]],
  ['procedure_54',['Recovery Procedure',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md389',1,'']]],
  ['processor_3a_20inject_5funread_5fcount_55',['8.3.3 Context Processor: inject_unread_count',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md247',1,'']]],
  ['profiling_56',['23.4 Monitoring and Profiling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md422',1,'']]],
  ['project_57',['4. Scope of the Project',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md200',1,'']]],
  ['project_20description_58',['2.2 Project Description',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md188',1,'']]],
  ['project_20goals_59',['2.3 Project Goals',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md189',1,'']]],
  ['project_20name_60',['2.1 Project Name',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md187',1,'']]],
  ['project_20overview_61',['2. Project Overview',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md186',1,'']]],
  ['project_20zip_62',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['property_20ip_63',['18.3 INTELLECTUAL PROPERTY (IP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md167',1,'']]],
  ['proposed_20solution_3a_20the_20intelligent_20approach_64',['1.3 PROPOSED SOLUTION: THE INTELLIGENT APPROACH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['protection_65',['H.1 LUNCH BREAK PROTECTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md135',1,'']]],
  ['py_66',['py',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md267',1,'10. Intelligent Scheduling Engine (scheduler.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md342',1,'18.2 Schedule Density Checker (check_density.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md343',1,'18.3 Schedule Integrity Checker (check_schedule.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'6.1 APPLICATION ENTRY POINT (app.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md241',1,'8. Application Entry Point (app.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'9. Routing and Controller Logic (routes.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md102',1,'B.1 CORE MODELS (models.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'B.2 THE SCHEDULING ALGORITHM (scheduler.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'CODE SNIPPET: The Requirement Fetcher (scheduler.py)']]],
  ['py_20logic_20excerpts_67',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['py_3a_68',['KEY COMPONENTS OF app.py:',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['pyinstaller_20spec_20file_69',['Appendix C: PyInstaller Spec File',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md481',1,'']]],
  ['python_20dependencies_70',['STEP 3: Install all Python dependencies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md332',1,'']]],
  ['python_20flask_71',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]]
];
