var searchData=
[
  ['mailbox_0',['4.2.10 TABLE: message (Mailbox)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['mailbox_20interface_1',['20.5 Mailbox Interface',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md366',1,'']]],
  ['mailbox_20logic_2',['6.2.6 INTERNAL MAILBOX LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md66',1,'']]],
  ['mailbox_20system_3',['15. Internal Messaging (Mailbox) System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md314',1,'']]],
  ['main_20js_4',['E.2 ANIMATION ENGINE (main.js)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md125',1,'']]],
  ['main_20scheduling_20method_5',['10.4 Main Scheduling Method',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md278',1,'']]],
  ['main_20views_6',['Dashboard and Main Views',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md394',1,'']]],
  ['management_7',['Management',['../md__r_e_a_d_m_e.html#autotoc_md173',1,'📊 Data Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md368',1,'20.7 Leave Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md413',1,'Connection Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md397',1,'Leave Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md386',1,'Memory Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md416',1,'Memory Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md429',1,'Session Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md396',1,'Timetable Management']]],
  ['management_20and_20substitution_20system_8',['14. Leave Management and Substitution System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md308',1,'']]],
  ['management_20system_9',['Management System',['../md__r_e_a_d_m_e.html',1,'Intelligent Timetable Management System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'Intelligent Timetable Management System']]],
  ['managing_20classrooms_10',['15.2.2 MANAGING CLASSROOMS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md156',1,'']]],
  ['managing_20departments_11',['15.2.1 MANAGING DEPARTMENTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md155',1,'']]],
  ['managing_20your_20academic_20life_12',['9.2 TEACHER GUIDE: MANAGING YOUR ACADEMIC LIFE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md88',1,'']]],
  ['manual_20edits_20and_20fine_20tuning_13',['15.5 MANUAL EDITS AND FINE-TUNING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md159',1,'']]],
  ['map_20row_20db_20object_14',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['march_202026_15',['DATE: MARCH 2026',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md150',1,'']]],
  ['master_20layout_20base_20html_16',['12.2 Master Layout (base.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md293',1,'']]],
  ['master_20layout_20templates_20base_20html_17',['J.1 THE MASTER LAYOUT (templates/base.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md141',1,'']]],
  ['master_20table_18',['A.5 TABLE: TIMETABLE_ENTRY (The Master Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'']]],
  ['matching_19',['Step 5: ROOM MATCHING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md274',1,'']]],
  ['matrix_20',['K.1 ROLE-BASED PERMISSION MATRIX',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md143',1,'']]],
  ['matrix_21',['11.4 Feature Access Matrix',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md289',1,'']]],
  ['medium_20term_20enhancements_20v2_200_22',['25.2 Medium-Term Enhancements (v2.0)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md449',1,'']]],
  ['memory_20management_23',['Memory Management',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md386',1,'Memory Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md416',1,'Memory Management']]],
  ['message_24',['Message',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md239',1,'7.13 Data Model: Message'],['../classmodels_1_1_message.html',1,'models.Message']]],
  ['message_20categories_25',['15.5 Message Categories',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md319',1,'']]],
  ['message_20mailbox_26',['4.2.10 TABLE: message (Mailbox)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['message_20route_27',['15.3 Compose Message Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md317',1,'']]],
  ['messaging_20features_28',['15.2 Messaging Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md316',1,'']]],
  ['messaging_20mailbox_20system_29',['15. Internal Messaging (Mailbox) System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md314',1,'']]],
  ['messaging_20system_30',['Messaging System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md398',1,'']]],
  ['metadata_31',['Metadata',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md97',1,'A.1 TABLE: DEPARTMENT (Metadata)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md98',1,'A.2 TABLE: COURSE (Metadata)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md99',1,'A.3 TABLE: TEACHER (Metadata)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md100',1,'A.4 TABLE: CLASSROOM (Metadata)']]],
  ['method_32',['10.4 Main Scheduling Method',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md278',1,'']]],
  ['metrics_33',['3.3 Success Metrics',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md198',1,'']]],
  ['migration_34',['Database Migration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md450',1,'']]],
  ['migrations_35',['6.3 UTILITY SCRIPTS (Checkers and Migrations)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'']]],
  ['mobile_20responsiveness_36',['Mobile Responsiveness',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md452',1,'']]],
  ['mobile_20smart_20notifications_37',['14.2 MOBILE SMART NOTIFICATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md147',1,'']]],
  ['mockup_38',['MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md127',1,'F.1 LOGIN PAGE MOCKUP'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md129',1,'F.2 ADMIN DASHBOARD MOCKUP'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md131',1,'F.3 TIMETABLE GRID MOCKUP']]],
  ['mode_39',['Mode',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md329',1,'17.2 Installation Steps (Web / Development Mode)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md245',1,'8.3.1 Desktop vs. Development Mode']]],
  ['model_40',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['model_20view_20controller_20mvc_20pattern_41',['3.2 THE MODEL-VIEW-CONTROLLER (MVC) PATTERN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['model_3a_20allocation_42',['7.8 Data Model: Allocation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md234',1,'']]],
  ['model_3a_20classroom_43',['7.7 Data Model: Classroom',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md233',1,'']]],
  ['model_3a_20course_44',['7.5 Data Model: Course',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md231',1,'']]],
  ['model_3a_20department_45',['7.4 Data Model: Department',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md230',1,'']]],
  ['model_3a_20leaverequest_46',['7.11 Data Model: LeaveRequest',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md237',1,'']]],
  ['model_3a_20message_47',['7.13 Data Model: Message',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md239',1,'']]],
  ['model_3a_20substitution_48',['7.12 Data Model: Substitution',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md238',1,'']]],
  ['model_3a_20teacher_49',['7.6 Data Model: Teacher',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md232',1,'']]],
  ['model_3a_20timetableentry_50',['7.9 Data Model: TimetableEntry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md235',1,'']]],
  ['model_3a_20user_51',['7.10 Data Model: User',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md236',1,'']]],
  ['models_52',['Models',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'4.2 DETAILED TABLE DEFINITIONS (SQLAlchemy Models)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md226',1,'7. Database Design and Data Models']]],
  ['models_20models_20py_53',['B.1 CORE MODELS (models.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md102',1,'']]],
  ['models_20py_54',['B.1 CORE MODELS (models.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md102',1,'']]],
  ['modern_20ui_20ux_55',['🎨 Modern UI/UX',['../md__r_e_a_d_m_e.html#autotoc_md172',1,'']]],
  ['modules_56',['Advanced Modules',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md457',1,'']]],
  ['monitoring_57',['Performance Monitoring',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md423',1,'']]],
  ['monitoring_20and_20profiling_58',['23.4 Monitoring and Profiling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md422',1,'']]],
  ['months_20_3a_20ai_20integration_59',['Phase 4 (18 months): AI Integration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md463',1,'']]],
  ['months_20_3a_20enterprise_20features_60',['Phase 3 (12 months): Enterprise Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md462',1,'']]],
  ['months_20_3a_20security_20stability_61',['Phase 1 (3 months): Security &amp;amp; Stability',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md460',1,'']]],
  ['months_20_3a_20user_20experience_62',['Phase 2 (6 months): User Experience',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md461',1,'']]],
  ['mvc_20pattern_63',['3.2 THE MODEL-VIEW-CONTROLLER (MVC) PATTERN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]]
];
