var searchData=
[
  ['lab_20blocks_203_20hour_20rule_0',['5.3 HANDLING PRACTICAL/LAB BLOCKS (3-Hour Rule)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['layer_1',['4.2.7 TABLE: user (Security Layer)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['layout_20base_20html_2',['12.2 Master Layout (base.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md293',1,'']]],
  ['layout_20templates_20base_20html_3',['J.1 THE MASTER LAYOUT (templates/base.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md141',1,'']]],
  ['layouts_4',['7.2 RESPONSIVE GRID LAYOUTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'']]],
  ['leave_20and_20substitution_20controller_5',['6.2.5 LEAVE AND SUBSTITUTION CONTROLLER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md64',1,'']]],
  ['leave_20management_6',['Leave Management',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md368',1,'20.7 Leave Management'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md397',1,'Leave Management']]],
  ['leave_20management_20and_20substitution_20system_7',['14. Leave Management and Substitution System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md308',1,'']]],
  ['leave_20request_20workflow_8',['14.2 Leave Request Workflow',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md310',1,'']]],
  ['leave_5frequest_9',['4.2.8 TABLE: leave_request',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md36',1,'']]],
  ['leaverequest_10',['LeaveRequest',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md237',1,'7.11 Data Model: LeaveRequest'],['../classmodels_1_1_leave_request.html',1,'models.LeaveRequest']]],
  ['leaverequest_20states_11',['14.3 LeaveRequest States',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md311',1,'']]],
  ['level_201_20route_20decorators_12',['Level 1 - Route Decorators',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md286',1,'']]],
  ['level_202_20in_20route_20role_20checks_13',['Level 2 - In-route Role Checks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md287',1,'']]],
  ['level_203_20template_20level_20visibility_14',['Level 3 - Template-Level Visibility',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md288',1,'']]],
  ['level_20system_20architecture_15',['3.1 HIGH-LEVEL SYSTEM ARCHITECTURE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md15',1,'']]],
  ['level_20visibility_16',['Level 3 - Template-Level Visibility',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md288',1,'']]],
  ['license_17',['⚖️ License',['../md__r_e_a_d_m_e.html#autotoc_md177',1,'']]],
  ['life_18',['9.2 TEACHER GUIDE: MANAGING YOUR ACADEMIC LIFE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md88',1,'']]],
  ['limit_20reached_19',['Issue: &quot;Department batch limit reached&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md376',1,'']]],
  ['limits_20',['Data Volume Limits',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md419',1,'']]],
  ['links_20are_20also_20cleaned_20up_21',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['list_20create_20routes_22',['List/Create Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md260',1,'']]],
  ['locked_20errors_23',['Issue: Database locked errors',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md380',1,'']]],
  ['log_20and_20resolution_24',['10.4 BUG LOG AND RESOLUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md93',1,'']]],
  ['logging_25',['Logging',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md442',1,'Audit Logging'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md424',1,'Database Query Logging']]],
  ['logic_26',['LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'5.4 ACTIVITY CLASS SLOT ALLOCATION LOGIC'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md62',1,'6.2.4 TIMETABLE DISPLAY LOGIC'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md66',1,'6.2.6 INTERNAL MAILBOX LOGIC'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'8.1 THE BULK INPUT PARSING LOGIC']]],
  ['logic_27',['Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md279',1,'10.5 Activity Class Assignment Logic'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md312',1,'14.4 Substitution Display Logic'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md112',1,'Slot Checking Logic...']]],
  ['logic_20examples_28',['19.4 Algorithm Logic Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md357',1,'']]],
  ['logic_20excerpts_29',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['logic_20for_20practical_20sessions_203_20hour_20slots_30',['Logic for Practical sessions (3-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['logic_20for_20theory_20sessions_201_20hour_20slots_31',['Logic for Theory sessions (1-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['logic_20routes_20py_32',['9. Routing and Controller Logic (routes.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'']]],
  ['logic_20to_20map_20row_20db_20object_33',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['login_34',['STEP 6: First Admin Login',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md335',1,'']]],
  ['login_20experience_35',['15.1 THE LOGIN EXPERIENCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md153',1,'']]],
  ['login_20form_36',['Login Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md402',1,'']]],
  ['login_20html_37',['LOGIN PAGE (login.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md295',1,'']]],
  ['login_20page_38',['20.1 Login Page',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md362',1,'']]],
  ['login_20page_20login_20html_39',['LOGIN PAGE (login.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md295',1,'']]],
  ['login_20page_20mockup_40',['F.1 LOGIN PAGE MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md127',1,'']]],
  ['login_20route_20implementation_41',['9.4.1 Login Route Implementation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md257',1,'']]],
  ['loginmanager_20configuration_42',['8.3.2 LoginManager Configuration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md246',1,'']]],
  ['logistics_43',['H.3 PRACTICAL SESSION LOGISTICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md137',1,'']]],
  ['logs_44',['16.2 INTERNAL AUDIT LOGS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md161',1,'']]],
  ['long_20term_20vision_20v3_200_45',['25.3 Long-Term Vision (v3.0)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md454',1,'']]],
  ['loop_20and_20validate_46',['3. Loop and Validate',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md109',1,'']]],
  ['lunch_20break_20protection_47',['H.1 LUNCH BREAK PROTECTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md135',1,'']]]
];
