var searchData=
[
  ['f_201_20login_20page_20mockup_0',['F.1 LOGIN PAGE MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md127',1,'']]],
  ['f_202_20admin_20dashboard_20mockup_1',['F.2 ADMIN DASHBOARD MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md129',1,'']]],
  ['f_203_20timetable_20grid_20mockup_2',['F.3 TIMETABLE GRID MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md131',1,'']]],
  ['failed_20to_20generate_20timetable_3',['Issue: &quot;Failed to generate timetable&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md373',1,'']]],
  ['fails_4',['Issue: CSV import fails',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md377',1,'']]],
  ['fair_20workload_20distribution_5',['H.2 FAIR WORKLOAD DISTRIBUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md136',1,'']]],
  ['false_20and_20informs_20the_20user_6',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['feature_7',['Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md302',1,'13. CSV Bulk Import Feature'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md321',1,'16. PDF Export Feature']]],
  ['feature_20access_20matrix_8',['11.4 Feature Access Matrix',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md289',1,'']]],
  ['features_9',['Features',['../md__r_e_a_d_m_e.html#autotoc_md169',1,'🚀 Key Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md316',1,'15.2 Messaging Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md453',1,'Advanced Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md202',1,'Core Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md458',1,'Enterprise Features'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md462',1,'Phase 3 (12 months): Enterprise Features']]],
  ['fetcher_20scheduler_20py_10',['CODE SNIPPET: The Requirement Fetcher (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['file_11',['Appendix C: PyInstaller Spec File',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md481',1,'']]],
  ['file_20structure_20analysis_12',['6.3 File Structure Analysis',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md221',1,'']]],
  ['file_20upload_20security_13',['File Upload Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md435',1,'']]],
  ['final_20documentation_20release_14',['[ FINAL DOCUMENTATION RELEASE ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md164',1,'']]],
  ['find_20all_20courses_20for_20a_20department_3a_15',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['fine_20tuning_16',['15.5 MANUAL EDITS AND FINE-TUNING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md159',1,'']]],
  ['first_17',['2. Sort requirements (Practicals first)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md108',1,'']]],
  ['first_20admin_20login_18',['STEP 6: First Admin Login',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md335',1,'']]],
  ['flask_19',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]],
  ['flask_20development_20server_20',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]],
  ['flask_20selection_20rationale_21',['Flask Selection Rationale',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md214',1,'']]],
  ['flow_20diagrams_20dfd_22',['3.4 DATA FLOW DIAGRAMS (DFD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'']]],
  ['flow_20example_23',['Flow Example',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md224',1,'Data Flow Example'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md223',1,'Request Flow Example']]],
  ['for_2010_20classes_24',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['for_20a_20department_3a_25',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['for_20each_20candidate_20slot_26',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['for_20institutional_20alignment_27',['Global Constants for institutional alignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md103',1,'']]],
  ['for_20practical_20sessions_203_20hour_20slots_28',['Logic for Practical sessions (3-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['for_20testing_29',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['for_20theory_20sessions_201_20hour_20slots_30',['Logic for Theory sessions (1-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['for_20today_3a_31',['Get timetable for today:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md349',1,'']]],
  ['form_32',['Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md406',1,'Classroom Form'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md405',1,'Course Form'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md403',1,'Department Form'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md402',1,'Login Form'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md404',1,'Teacher Form'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md407',1,'Timetable Entry Form']]],
  ['form_20data_20parameters_33',['22.3 Form Data Parameters',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md401',1,'']]],
  ['form_20validation_3a_34',['Form validation:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md356',1,'']]],
  ['formats_35',['13.4 Sample CSV Formats',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md306',1,'']]],
  ['frameworks_36',['27.1 Documentation and Frameworks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md472',1,'']]],
  ['from_20backup_37',['16.3 RESTORING FROM BACKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md162',1,'']]],
  ['frontend_20design_38',['12. User Interface and Frontend Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md291',1,'']]],
  ['frontend_20performance_39',['Frontend Performance',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md385',1,'']]],
  ['frontend_20technologies_40',['5.2 Frontend Technologies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md211',1,'']]],
  ['full_20technical_20documentation_41',['Full Technical Documentation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md179',1,'']]],
  ['function_42',['Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md264',1,'9.8 Conflict Detection Function'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md265',1,'9.9 Smart Slot Suggestion Function']]],
  ['functional_20requirements_43',['2.3 NON-FUNCTIONAL REQUIREMENTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md12',1,'']]],
  ['functional_20requirements_20breakdown_44',['2.2 FUNCTIONAL REQUIREMENTS BREAKDOWN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['future_20enhancements_45',['25. Future Enhancements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md444',1,'']]],
  ['future_20potential_46',['Future Potential',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md469',1,'']]],
  ['future_20work_20ai_20integration_47',['11.3 FUTURE WORK (AI INTEGRATION)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md96',1,'']]]
];
