var searchData=
[
  ['sample_20classrooms_0',['Sample Classrooms',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md486',1,'']]],
  ['sample_20courses_1',['Sample Courses',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md485',1,'']]],
  ['sample_20csv_20formats_2',['13.4 Sample CSV Formats',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md306',1,'']]],
  ['sample_20data_20for_20testing_3',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['sample_20departments_4',['Sample Departments',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md483',1,'']]],
  ['sample_20teachers_5',['Sample Teachers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md484',1,'']]],
  ['sanitization_6',['Input Sanitization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md440',1,'']]],
  ['satisfaction_20problem_20csp_7',['5.1 THE CONSTRAINT-SATISFACTION PROBLEM (CSP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['satisfaction_20problem_20csp_20model_8',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['scalability_20considerations_9',['G.3 SCALABILITY CONSIDERATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md134',1,'']]],
  ['scalability_20considerations_10',['23.3 Scalability Considerations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md418',1,'']]],
  ['scenarios_11',['18.4 Test Scenarios',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md344',1,'']]],
  ['schedule_12',['1. Clear existing schedule',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md107',1,'']]],
  ['schedule_20density_20checker_20check_5fdensity_20py_13',['18.2 Schedule Density Checker (check_density.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md342',1,'']]],
  ['schedule_20integrity_20checker_20check_5fschedule_20py_14',['18.3 Schedule Integrity Checker (check_schedule.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md343',1,'']]],
  ['scheduler_15',['🧠 Intelligent Scheduler',['../md__r_e_a_d_m_e.html#autotoc_md170',1,'']]],
  ['scheduler_20class_20constructor_16',['10.3 Scheduler Class Constructor',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md277',1,'']]],
  ['scheduler_20py_17',['scheduler py',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md267',1,'10. Intelligent Scheduling Engine (scheduler.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'B.2 THE SCHEDULING ALGORITHM (scheduler.py)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'CODE SNIPPET: The Requirement Fetcher (scheduler.py)']]],
  ['scheduler_20stress_20tests_18',['C.3 SCHEDULER STRESS TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md122',1,'']]],
  ['schedules_19',['Randomized &apos;Domain&apos; prevents repetitive schedules',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md111',1,'']]],
  ['scheduling_20',['AI-Enhanced Scheduling',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md455',1,'']]],
  ['scheduling_20algorithm_20design_21',['10.2 Scheduling Algorithm Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md269',1,'']]],
  ['scheduling_20algorithm_20scheduler_20py_22',['B.2 THE SCHEDULING ALGORITHM (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'']]],
  ['scheduling_20controls_23',['6.2.3 THE SCHEDULING CONTROLS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['scheduling_20engine_20scheduler_20py_24',['10. Intelligent Scheduling Engine (scheduler.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md267',1,'']]],
  ['scheduling_20heuristics_25',['5.2 PRIORITY SCHEDULING HEURISTICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['scheduling_20method_26',['10.4 Main Scheduling Method',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md278',1,'']]],
  ['schema_20sql_27',['Appendix B: Database Schema SQL',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md480',1,'']]],
  ['scope_28',['Scope',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md201',1,'4.1 In Scope'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md204',1,'4.2 Out of Scope'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md203',1,'Technical Scope']]],
  ['scope_20of_20the_20project_29',['4. Scope of the Project',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md200',1,'']]],
  ['screenshots_20and_20visual_20guide_30',['20. Screenshots and Visual Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md361',1,'']]],
  ['scripts_20checkers_20and_20migrations_31',['6.3 UTILITY SCRIPTS (Checkers and Migrations)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'']]],
  ['search_20space_32',['13.2 THE HEURISTIC SEARCH SPACE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md139',1,'']]],
  ['search_20space_20is_20too_20small_20e_20g_20only_201_20room_20for_2010_20classes_33',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['secondary_20objectives_34',['3.2 Secondary Objectives',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md197',1,'']]],
  ['sections_20explained_35',['8.3 Key Sections Explained',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md244',1,'']]],
  ['security_36',['Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md427',1,'24.1 Authentication Security'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md430',1,'24.2 Authorization Security'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md433',1,'24.3 Data Security'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md436',1,'24.4 Network Security'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md434',1,'Database Security'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md435',1,'File Upload Security']]],
  ['security_20analysis_37',['24. Security Analysis',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md426',1,'']]],
  ['security_20and_20best_20practices_38',['27.5 Security and Best Practices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md476',1,'']]],
  ['security_20best_20practices_39',['24.5 Security Best Practices',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md439',1,'']]],
  ['security_20improvements_40',['Security Improvements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md446',1,'']]],
  ['security_20layer_41',['4.2.7 TABLE: user (Security Layer)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['security_20penetration_20testing_42',['10.3 SECURITY PENETRATION TESTING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md92',1,'']]],
  ['security_20stability_43',['Phase 1 (3 months): Security &amp;amp; Stability',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md460',1,'']]],
  ['selection_20rationale_44',['Selection Rationale',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md214',1,'Flask Selection Rationale'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md215',1,'SQLite Selection Rationale']]],
  ['selection_3a_45',['Random slot selection:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md359',1,'']]],
  ['semester_46',['9.1 ADMINISTRATOR GUIDE: SETTING UP A NEW SEMESTER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'']]],
  ['server_47',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]],
  ['session_20logistics_48',['H.3 PRACTICAL SESSION LOGISTICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md137',1,'']]],
  ['session_20management_49',['Session Management',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md429',1,'']]],
  ['sessions_201_20hour_20slots_50',['Logic for Theory sessions (1-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['sessions_203_20hour_20slots_51',['Logic for Practical sessions (3-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['setting_20up_20a_20new_20semester_52',['9.1 ADMINISTRATOR GUIDE: SETTING UP A NEW SEMESTER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'']]],
  ['setup_20workflow_20after_20install_53',['17.3 Initial Setup Workflow (After Install)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md336',1,'']]],
  ['short_20term_20enhancements_20v1_201_54',['25.1 Short-Term Enhancements (v1.1)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md445',1,'']]],
  ['showing_20on_20timetable_55',['Issue: Substitution not showing on timetable',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md381',1,'']]],
  ['slot_56',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['slot_20allocation_20logic_57',['5.4 ACTIVITY CLASS SLOT ALLOCATION LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['slot_20checking_20logic_58',['Slot Checking Logic...',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md112',1,'']]],
  ['slot_20selection_3a_59',['Random slot selection:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md359',1,'']]],
  ['slot_20suggestion_20function_60',['9.9 Smart Slot Suggestion Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md265',1,'']]],
  ['slots_61',['slots',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'Logic for Practical sessions (3-hour slots)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'Logic for Theory sessions (1-hour slots)']]],
  ['small_20e_20g_20only_201_20room_20for_2010_20classes_62',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['smart_20notifications_63',['14.2 MOBILE SMART NOTIFICATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md147',1,'']]],
  ['smart_20slot_20suggestion_20function_64',['9.9 Smart Slot Suggestion Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md265',1,'']]],
  ['snippet_3a_20the_20requirement_20fetcher_20scheduler_20py_65',['CODE SNIPPET: The Requirement Fetcher (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['snippets_66',['19. Code Examples and Snippets',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md346',1,'']]],
  ['software_20prerequisites_67',['2.4 HARDWARE AND SOFTWARE PREREQUISITES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md13',1,'']]],
  ['software_20requirements_68',['Software Requirements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md193',1,'']]],
  ['solution_3a_20the_20intelligent_20approach_69',['1.3 PROPOSED SOLUTION: THE INTELLIGENT APPROACH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['solutions_70',['21.1 Common Issues and Solutions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md372',1,'']]],
  ['sort_20by_20duration_20descending_71',['Priority Hack: Sort by duration descending',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md110',1,'']]],
  ['sort_20requirements_20practicals_20first_72',['2. Sort requirements (Practicals first)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md108',1,'']]],
  ['source_20code_73',['8.2 Complete Source Code',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md243',1,'']]],
  ['space_74',['13.2 THE HEURISTIC SEARCH SPACE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md139',1,'']]],
  ['space_20is_20too_20small_20e_20g_20only_201_20room_20for_2010_20classes_75',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['spec_20file_76',['Appendix C: PyInstaller Spec File',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md481',1,'']]],
  ['specifications_77',['8.2 DETAILED CSV SPECIFICATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md79',1,'']]],
  ['sql_78',['Appendix B: Database Schema SQL',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md480',1,'']]],
  ['sqlalchemy_20models_79',['4.2 DETAILED TABLE DEFINITIONS (SQLAlchemy Models)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'']]],
  ['sqlite_20selection_20rationale_80',['SQLite Selection Rationale',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md215',1,'']]],
  ['stability_81',['Phase 1 (3 months): Security &amp;amp; Stability',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md460',1,'']]],
  ['stack_82',['Stack',['../md__r_e_a_d_m_e.html#autotoc_md174',1,'🛠️ Technical Stack'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md209',1,'5. Technology Stack'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md213',1,'5.4 Why This Stack?']]],
  ['stack_20deep_20dive_20why_20python_20flask_83',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]],
  ['start_84',['Issue: Application won&apos;t start',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md379',1,'']]],
  ['started_85',['🏃 Getting Started',['../md__r_e_a_d_m_e.html#autotoc_md176',1,'']]],
  ['statement_86',['1.2 THE CORE PROBLEM STATEMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md6',1,'']]],
  ['states_87',['14.3 LeaveRequest States',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md311',1,'']]],
  ['status_20codes_88',['22.2 HTTP Status Codes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md400',1,'']]],
  ['step_201_3a_20clone_20the_20repository_20or_20extract_20the_20project_20zip_89',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['step_201_3a_20requirement_20collection_90',['Step 1: REQUIREMENT COLLECTION',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md270',1,'']]],
  ['step_202_3a_20create_20and_20activate_20a_20virtual_20environment_20recommended_91',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['step_202_3a_20prioritization_92',['Step 2: PRIORITIZATION',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md271',1,'']]],
  ['step_203_3a_20domain_20building_93',['Step 3: DOMAIN BUILDING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md272',1,'']]],
  ['step_203_3a_20install_20all_20python_20dependencies_94',['STEP 3: Install all Python dependencies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md332',1,'']]],
  ['step_204_3a_20constraint_20checking_20for_20each_20candidate_20slot_95',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['step_204_3a_20run_20the_20flask_20development_20server_96',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]],
  ['step_205_3a_20access_20the_20application_97',['STEP 5: Access the application',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md334',1,'']]],
  ['step_205_3a_20room_20matching_98',['Step 5: ROOM MATCHING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md274',1,'']]],
  ['step_206_3a_20activity_20class_20assignment_99',['Step 6: ACTIVITY CLASS ASSIGNMENT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md275',1,'']]],
  ['step_206_3a_20first_20admin_20login_100',['STEP 6: First Admin Login',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md335',1,'']]],
  ['step_207_3a_20database_20commit_101',['Step 7: DATABASE COMMIT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md276',1,'']]],
  ['steps_20web_20development_20mode_102',['17.2 Installation Steps (Web / Development Mode)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md329',1,'']]],
  ['stochastic_20optimization_103',['14.1 TOWARDS STOCHASTIC OPTIMIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md146',1,'']]],
  ['storage_104',['Password Storage',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md428',1,'']]],
  ['strategies_105',['Caching Strategies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md415',1,'']]],
  ['strategy_106',['10.1 TESTING STRATEGY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md90',1,'']]],
  ['strategy_107',['Indexing Strategy',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md411',1,'']]],
  ['stress_20tests_108',['C.3 SCHEDULER STRESS TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md122',1,'']]],
  ['structure_109',['12.4 Timetable Grid Structure',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md299',1,'']]],
  ['structure_20analysis_110',['6.3 File Structure Analysis',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md221',1,'']]],
  ['student_20dashboard_111',['7.4.3 THE STUDENT DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md77',1,'']]],
  ['student_20guide_3a_20attending_20classes_112',['9.3 STUDENT GUIDE: ATTENDING CLASSES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md89',1,'']]],
  ['study_113',['1.4 OBJECTIVES OF THE STUDY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['subjects_20courses_20subjects_20csv_114',['A. SUBJECTS/COURSES (subjects.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['subjects_20csv_115',['A. SUBJECTS/COURSES (subjects.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['substitution_116',['7.12 Data Model: Substitution',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md238',1,'']]],
  ['substitution_117',['4.2.9 TABLE: substitution',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'']]],
  ['substitution_20controller_118',['6.2.5 LEAVE AND SUBSTITUTION CONTROLLER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md64',1,'']]],
  ['substitution_20display_20logic_119',['14.4 Substitution Display Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md312',1,'']]],
  ['substitution_20not_20showing_20on_20timetable_120',['Issue: Substitution not showing on timetable',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md381',1,'']]],
  ['substitution_20system_121',['14. Leave Management and Substitution System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md308',1,'']]],
  ['success_20metrics_122',['3.3 Success Metrics',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md198',1,'']]],
  ['successful_20assignment_123',['Record successful assignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md114',1,'']]],
  ['suggestion_20function_124',['9.9 Smart Slot Suggestion Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md265',1,'']]],
  ['summary_125',['Summary',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md280',1,'10.6 Constraint Summary'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md259',1,'9.6 CRUD Routes Summary']]],
  ['supported_20import_20types_126',['13.2 Supported Import Types',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md304',1,'']]],
  ['system_127',['System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md308',1,'14. Leave Management and Substitution System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md314',1,'15. Internal Messaging (Mailbox) System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md195',1,'3. Objectives of the System'],['../md__r_e_a_d_m_e.html',1,'Intelligent Timetable Management System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'Intelligent Timetable Management System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md398',1,'Messaging System']]],
  ['system_20architecture_128',['3.1 HIGH-LEVEL SYSTEM ARCHITECTURE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md15',1,'']]],
  ['system_20architecture_129',['6. System Architecture',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md218',1,'']]],
  ['system_20requirements_130',['2.5 System Requirements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md191',1,'']]]
];
