var searchData=
[
  ['c_201_20authentication_20tests_0',['C.1 AUTHENTICATION TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md120',1,'']]],
  ['c_202_20database_20integrity_20tests_1',['C.2 DATABASE INTEGRITY TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md121',1,'']]],
  ['c_203_20scheduler_20stress_20tests_2',['C.3 SCHEDULER STRESS TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md122',1,'']]],
  ['c_204_20user_20interface_20ui_20tests_3',['C.4 USER INTERFACE (UI) TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md123',1,'']]],
  ['c_20allocations_20allocations_20csv_4',['C. ALLOCATIONS (allocations.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'']]],
  ['c_3a_20pyinstaller_20spec_20file_5',['Appendix C: PyInstaller Spec File',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md481',1,'']]],
  ['caching_20strategies_6',['Caching Strategies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md415',1,'']]],
  ['candidate_20slot_7',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['canvas_20animations_20background_20engine_8',['7.3 DYNAMIC CANVAS ANIMATIONS (Background Engine)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['capabilities_9',['Integration Capabilities',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md456',1,'']]],
  ['cascade_20deletes_20ensure_20that_20if_20a_20department_20is_20removed_10',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['categories_11',['15.5 Message Categories',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md319',1,'']]],
  ['cell_3a_12',['Display timetable cell:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md352',1,'']]],
  ['certificate_13',['0.2 CERTIFICATE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md4',1,'']]],
  ['check_20teacher_20availability_3a_14',['Check teacher availability:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md350',1,'']]],
  ['check_5fdensity_20py_15',['18.2 Schedule Density Checker (check_density.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md342',1,'']]],
  ['check_5fschedule_20py_16',['18.3 Schedule Integrity Checker (check_schedule.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md343',1,'']]],
  ['checker_20check_5fdensity_20py_17',['18.2 Schedule Density Checker (check_density.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md342',1,'']]],
  ['checker_20check_5fschedule_20py_18',['18.3 Schedule Integrity Checker (check_schedule.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md343',1,'']]],
  ['checkers_20and_20migrations_19',['6.3 UTILITY SCRIPTS (Checkers and Migrations)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'']]],
  ['checking_20for_20each_20candidate_20slot_20',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['checking_20logic_21',['Slot Checking Logic...',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md112',1,'']]],
  ['checking_3a_22',['Constraint checking:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md358',1,'']]],
  ['checks_23',['Level 2 - In-route Role Checks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md287',1,'']]],
  ['class_20assignment_24',['Step 6: ACTIVITY CLASS ASSIGNMENT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md275',1,'']]],
  ['class_20assignment_20logic_25',['10.5 Activity Class Assignment Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md279',1,'']]],
  ['class_20constructor_26',['10.3 Scheduler Class Constructor',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md277',1,'']]],
  ['class_20slot_20allocation_20logic_27',['5.4 ACTIVITY CLASS SLOT ALLOCATION LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['classes_28',['9.3 STUDENT GUIDE: ATTENDING CLASSES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md89',1,'']]],
  ['classes_29',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['classroom_30',['7.7 Data Model: Classroom',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md233',1,'']]],
  ['classroom_31',['4.2.4 TABLE: classroom',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md28',1,'']]],
  ['classroom_20form_32',['Classroom Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md406',1,'']]],
  ['classroom_20is_20already_20occupied_33',['Issue: &quot;Classroom is already occupied&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md375',1,'']]],
  ['classroom_20metadata_34',['A.4 TABLE: CLASSROOM (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md100',1,'']]],
  ['classrooms_35',['15.2.2 MANAGING CLASSROOMS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md156',1,'']]],
  ['classrooms_36',['Sample Classrooms',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md486',1,'']]],
  ['cleaned_20up_37',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['clear_20existing_20schedule_38',['1. Clear existing schedule',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md107',1,'']]],
  ['clone_20the_20repository_20or_20extract_20the_20project_20zip_39',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['cloud_20deployment_20heroku_20aws_20azure_40',['11.1 CLOUD DEPLOYMENT (HEROKU / AWS / AZURE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md94',1,'']]],
  ['code_41',['8.2 Complete Source Code',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md243',1,'']]],
  ['code_20examples_20and_20snippets_42',['19. Code Examples and Snippets',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md346',1,'']]],
  ['code_20snippet_3a_20the_20requirement_20fetcher_20scheduler_20py_43',['CODE SNIPPET: The Requirement Fetcher (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['codes_44',['G.1 COMMON ERROR CODES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md132',1,'']]],
  ['codes_45',['22.2 HTTP Status Codes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md400',1,'']]],
  ['collection_46',['Step 1: REQUIREMENT COLLECTION',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md270',1,'']]],
  ['commit_47',['Step 7: DATABASE COMMIT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md276',1,'']]],
  ['common_20error_20codes_48',['G.1 COMMON ERROR CODES',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md132',1,'']]],
  ['common_20issues_20and_20solutions_49',['21.1 Common Issues and Solutions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md372',1,'']]],
  ['complete_20source_20code_50',['8.2 Complete Source Code',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md243',1,'']]],
  ['complexity_20analysis_20big_20o_20notation_51',['13.3 COMPLEXITY ANALYSIS (Big-O Notation)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md140',1,'']]],
  ['compliance_52',['18.2 DATA PRIVACY &amp;amp; GDPR COMPLIANCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md166',1,'']]],
  ['component_20interactions_53',['6.4 Component Interactions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md222',1,'']]],
  ['components_20of_20app_20py_3a_54',['KEY COMPONENTS OF app.py:',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['compose_20message_20route_55',['15.3 Compose Message Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md317',1,'']]],
  ['conclusion_56',['26. Conclusion',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md465',1,'']]],
  ['concurrent_20users_57',['Concurrent Users',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md420',1,'']]],
  ['configuration_58',['8.3.2 LoginManager Configuration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md246',1,'']]],
  ['conflict_20detection_20algorithm_20walkthrough_59',['5.5 CONFLICT DETECTION ALGORITHM WALKTHROUGH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['conflict_20detection_20function_60',['9.8 Conflict Detection Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md264',1,'']]],
  ['connection_20management_61',['Connection Management',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md413',1,'']]],
  ['considerations_62',['G.3 SCALABILITY CONSIDERATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md134',1,'']]],
  ['considerations_63',['Considerations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md409',1,'23. Performance Considerations'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md418',1,'23.3 Scalability Considerations'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md438',1,'CORS Considerations']]],
  ['constants_64',['7.3 Global Constants',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md229',1,'']]],
  ['constants_20for_20institutional_20alignment_65',['Global Constants for institutional alignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md103',1,'']]],
  ['constraint_20checking_20for_20each_20candidate_20slot_66',['Step 4: CONSTRAINT CHECKING (for each candidate slot)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md273',1,'']]],
  ['constraint_20checking_3a_67',['Constraint checking:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md358',1,'']]],
  ['constraint_20satisfaction_20problem_20csp_68',['5.1 THE CONSTRAINT-SATISFACTION PROBLEM (CSP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['constraint_20satisfaction_20problem_20csp_20model_69',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['constraint_20summary_70',['10.6 Constraint Summary',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md280',1,'']]],
  ['constraints_71',['Constraints',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md205',1,'4.3 Assumptions and Constraints'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md207',1,'Constraints']]],
  ['constructor_72',['10.3 Scheduler Class Constructor',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md277',1,'']]],
  ['contents_73',['Table of Contents',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md181',1,'']]],
  ['context_20processor_3a_20inject_5funread_5fcount_74',['8.3.3 Context Processor: inject_unread_count',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md247',1,'']]],
  ['control_75',['Role-Based Access Control',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md431',1,'']]],
  ['control_20implementation_76',['11.3 Access Control Implementation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md285',1,'']]],
  ['control_20rbac_77',['Control RBAC',['../md__r_e_a_d_m_e.html#autotoc_md171',1,'👥 Role-Based Access Control (RBAC)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md282',1,'11. Role-Based Access Control (RBAC)']]],
  ['controller_78',['6.2.5 LEAVE AND SUBSTITUTION CONTROLLER',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md64',1,'']]],
  ['controller_20logic_20routes_20py_79',['9. Routing and Controller Logic (routes.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'']]],
  ['controller_20mvc_20pattern_80',['3.2 THE MODEL-VIEW-CONTROLLER (MVC) PATTERN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['controller_20routes_20py_20logic_20excerpts_81',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['controllers_20routes_20py_82',['6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['controls_83',['6.2.3 THE SCHEDULING CONTROLS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['core_20features_84',['Core Features',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md202',1,'']]],
  ['core_20models_20models_20py_85',['B.1 CORE MODELS (models.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md102',1,'']]],
  ['core_20problem_20statement_86',['1.2 THE CORE PROBLEM STATEMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md6',1,'']]],
  ['corrupted_87',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['cors_20considerations_88',['CORS Considerations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md438',1,'']]],
  ['course_89',['7.5 Data Model: Course',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md231',1,'']]],
  ['course_90',['4.2.2 TABLE: course',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'']]],
  ['course_20form_91',['Course Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md405',1,'']]],
  ['course_20metadata_92',['A.2 TABLE: COURSE (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md98',1,'']]],
  ['courses_93',['Sample Courses',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md485',1,'']]],
  ['courses_20and_20teacher_20links_20are_20also_20cleaned_20up_94',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['courses_20for_20a_20department_3a_95',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['courses_20subjects_20csv_96',['A. SUBJECTS/COURSES (subjects.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['create_20and_20activate_20a_20virtual_20environment_20recommended_97',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['create_20routes_98',['List/Create Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md260',1,'']]],
  ['crud_99',['6.2.2 DATA ADMINISTRATION (CRUD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['crud_20operations_100',['CRUD Operations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md395',1,'']]],
  ['crud_20routes_20summary_101',['9.6 CRUD Routes Summary',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md259',1,'']]],
  ['csp_102',['5.1 THE CONSTRAINT-SATISFACTION PROBLEM (CSP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['csp_20model_103',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['css_104',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['css_20rationale_105',['Vanilla CSS Rationale',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md216',1,'']]],
  ['csv_106',['15.3.3 BULK DATA UPLOAD (CSV)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md157',1,'']]],
  ['csv_107',['csv',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'A. SUBJECTS/COURSES (subjects.csv)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md83',1,'B. TEACHERS (teachers.csv)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'C. ALLOCATIONS (allocations.csv)']]],
  ['csv_20bulk_20import_20feature_108',['13. CSV Bulk Import Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md302',1,'']]],
  ['csv_20formats_109',['13.4 Sample CSV Formats',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md306',1,'']]],
  ['csv_20import_20fails_110',['Issue: CSV import fails',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md377',1,'']]],
  ['csv_20import_20route_111',['13.3 CSV Import Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md305',1,'']]],
  ['csv_20imports_112',['8.3 ERROR HANDLING IN CSV IMPORTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md86',1,'']]],
  ['csv_20specifications_113',['8.2 DETAILED CSV SPECIFICATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md79',1,'']]],
  ['csv_20upload_114',['20.6 CSV Upload',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md367',1,'']]]
];
