var searchData=
[
  ['if_20a_20department_20is_20removed_0',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['if_20the_20search_20space_20is_20too_20small_20e_20g_20only_201_20room_20for_2010_20classes_1',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['impact_20assessment_2',['1.5 IMPACT ASSESSMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md9',1,'']]],
  ['implementation_3',['Implementation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md285',1,'11.3 Access Control Implementation'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md257',1,'9.4.1 Login Route Implementation']]],
  ['implementation_20roadmap_4',['25.4 Implementation Roadmap',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md459',1,'']]],
  ['import_20fails_5',['Issue: CSV import fails',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md377',1,'']]],
  ['import_20feature_6',['13. CSV Bulk Import Feature',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md302',1,'']]],
  ['import_20route_7',['13.3 CSV Import Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md305',1,'']]],
  ['import_20types_8',['13.2 Supported Import Types',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md304',1,'']]],
  ['imports_9',['8.3 ERROR HANDLING IN CSV IMPORTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md86',1,'']]],
  ['improvements_10',['Security Improvements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md446',1,'']]],
  ['in_20csv_20imports_11',['8.3 ERROR HANDLING IN CSV IMPORTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md86',1,'']]],
  ['in_20room_12',['Place in Room...',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md113',1,'']]],
  ['in_20route_20role_20checks_13',['Level 2 - In-route Role Checks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md287',1,'']]],
  ['in_20scope_14',['4.1 In Scope',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md201',1,'']]],
  ['index_20css_15',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['indexing_20strategy_16',['Indexing Strategy',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md411',1,'']]],
  ['informs_20the_20user_17',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['initial_20setup_20workflow_20after_20install_18',['17.3 Initial Setup Workflow (After Install)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md336',1,'']]],
  ['initialization_19',['8.3.6 Database Initialization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md250',1,'']]],
  ['initialization_3a_20',['Particle animation initialization:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md355',1,'']]],
  ['inject_5funread_5fcount_21',['8.3.3 Context Processor: inject_unread_count',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md247',1,'']]],
  ['input_20parsing_20logic_22',['8.1 THE BULK INPUT PARSING LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['input_20sanitization_23',['Input Sanitization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md440',1,'']]],
  ['input_20validation_24',['Input Validation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md432',1,'']]],
  ['install_25',['17.3 Initial Setup Workflow (After Install)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md336',1,'']]],
  ['install_20all_20python_20dependencies_26',['STEP 3: Install all Python dependencies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md332',1,'']]],
  ['installation_20and_20deployment_20guide_27',['17. Installation and Deployment Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md327',1,'']]],
  ['installation_20steps_20web_20development_20mode_28',['17.2 Installation Steps (Web / Development Mode)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md329',1,'']]],
  ['institutional_20alignment_29',['Global Constants for institutional alignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md103',1,'']]],
  ['institutional_20data_20ethics_30',['18.1 INSTITUTIONAL DATA ETHICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md165',1,'']]],
  ['institutional_20requirements_31',['2.1 INSTITUTIONAL REQUIREMENTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'']]],
  ['integration_32',['11.3 FUTURE WORK (AI INTEGRATION)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md96',1,'']]],
  ['integration_33',['Phase 4 (18 months): AI Integration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md463',1,'']]],
  ['integration_20capabilities_34',['Integration Capabilities',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md456',1,'']]],
  ['integrity_20checker_20check_5fschedule_20py_35',['18.3 Schedule Integrity Checker (check_schedule.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md343',1,'']]],
  ['integrity_20tests_36',['C.2 DATABASE INTEGRITY TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md121',1,'']]],
  ['intellectual_20property_20ip_37',['18.3 INTELLECTUAL PROPERTY (IP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md167',1,'']]],
  ['intelligent_20approach_38',['1.3 PROPOSED SOLUTION: THE INTELLIGENT APPROACH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['intelligent_20scheduler_39',['🧠 Intelligent Scheduler',['../md__r_e_a_d_m_e.html#autotoc_md170',1,'']]],
  ['intelligent_20scheduling_20engine_20scheduler_20py_40',['10. Intelligent Scheduling Engine (scheduler.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md267',1,'']]],
  ['intelligent_20timetable_20management_20system_41',['Intelligent Timetable Management System',['../md__r_e_a_d_m_e.html',1,'Intelligent Timetable Management System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'Intelligent Timetable Management System']]],
  ['interactions_42',['6.4 Component Interactions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md222',1,'']]],
  ['interface_43',['20.5 Mailbox Interface',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md366',1,'']]],
  ['interface_20and_20frontend_20design_44',['12. User Interface and Frontend Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md291',1,'']]],
  ['interface_20ui_20tests_45',['C.4 USER INTERFACE (UI) TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md123',1,'']]],
  ['internal_20audit_20logs_46',['16.2 INTERNAL AUDIT LOGS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md161',1,'']]],
  ['internal_20mailbox_20logic_47',['6.2.6 INTERNAL MAILBOX LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md66',1,'']]],
  ['internal_20messaging_20mailbox_20system_48',['15. Internal Messaging (Mailbox) System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md314',1,'']]],
  ['introduction_49',['1. Introduction',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md183',1,'']]],
  ['invalid_20username_20or_20password_50',['Issue: &quot;Invalid username or password&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md374',1,'']]],
  ['ip_51',['18.3 INTELLECTUAL PROPERTY (IP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md167',1,'']]],
  ['is_20already_20occupied_52',['Issue: &quot;Classroom is already occupied&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md375',1,'']]],
  ['is_20blank_20or_20corrupted_53',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['is_20removed_54',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['is_20too_20small_20e_20g_20only_201_20room_20for_2010_20classes_55',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['issue_3a_20application_20won_20t_20start_56',['Issue: Application won&apos;t start',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md379',1,'']]],
  ['issue_3a_20classroom_20is_20already_20occupied_57',['Issue: &quot;Classroom is already occupied&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md375',1,'']]],
  ['issue_3a_20csv_20import_20fails_58',['Issue: CSV import fails',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md377',1,'']]],
  ['issue_3a_20database_20locked_20errors_59',['Issue: Database locked errors',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md380',1,'']]],
  ['issue_3a_20department_20batch_20limit_20reached_60',['Issue: &quot;Department batch limit reached&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md376',1,'']]],
  ['issue_3a_20failed_20to_20generate_20timetable_61',['Issue: &quot;Failed to generate timetable&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md373',1,'']]],
  ['issue_3a_20invalid_20username_20or_20password_62',['Issue: &quot;Invalid username or password&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md374',1,'']]],
  ['issue_3a_20particle_20background_20not_20animating_63',['Issue: Particle background not animating',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md382',1,'']]],
  ['issue_3a_20pdf_20export_20is_20blank_20or_20corrupted_64',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['issue_3a_20substitution_20not_20showing_20on_20timetable_65',['Issue: Substitution not showing on timetable',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md381',1,'']]],
  ['issues_20and_20solutions_66',['21.1 Common Issues and Solutions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md372',1,'']]],
  ['it_20works_67',['16.2 How It Works',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md323',1,'']]],
  ['its_20courses_20and_20teacher_20links_20are_20also_20cleaned_20up_68',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]]
];
