var searchData=
[
  ['random_20slot_20selection_3a_0',['Random slot selection:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md359',1,'']]],
  ['randomized_20domain_20prevents_20repetitive_20schedules_1',['Randomized &apos;Domain&apos; prevents repetitive schedules',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md111',1,'']]],
  ['rationale_2',['Rationale',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md214',1,'Flask Selection Rationale'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md215',1,'SQLite Selection Rationale'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md216',1,'Vanilla CSS Rationale']]],
  ['rbac_3',['RBAC',['../md__r_e_a_d_m_e.html#autotoc_md171',1,'👥 Role-Based Access Control (RBAC)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md282',1,'11. Role-Based Access Control (RBAC)']]],
  ['reached_4',['Issue: &quot;Department batch limit reached&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md376',1,'']]],
  ['recommendation_5',['HTTPS Recommendation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md437',1,'']]],
  ['recommended_6',['STEP 2: Create and activate a virtual environment (recommended)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md331',1,'']]],
  ['record_20successful_20assignment_7',['Record successful assignment',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md114',1,'']]],
  ['recovery_8',['21.3 Backup and Recovery',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md387',1,'']]],
  ['recovery_20procedure_9',['Recovery Procedure',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md389',1,'']]],
  ['reference_10',['22. API Reference',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md391',1,'']]],
  ['references_11',['27. References',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md471',1,'']]],
  ['registration_12',['6.2.1 AUTHENTICATION AND REGISTRATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md56',1,'']]],
  ['registration_13',['8.3.5 Blueprint Registration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md249',1,'']]],
  ['relationship_20diagram_14',['7.2 Entity Relationship Diagram',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md228',1,'']]],
  ['release_15',['[ FINAL DOCUMENTATION RELEASE ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md164',1,'']]],
  ['removed_16',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['rendering_20examples_17',['19.2 Template Rendering Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md351',1,'']]],
  ['repetitive_20schedules_18',['Randomized &apos;Domain&apos; prevents repetitive schedules',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md111',1,'']]],
  ['repository_20or_20extract_20the_20project_20zip_19',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['request_20flow_20example_20',['Request Flow Example',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md223',1,'']]],
  ['request_20workflow_21',['14.2 Leave Request Workflow',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md310',1,'']]],
  ['requirement_20collection_22',['Step 1: REQUIREMENT COLLECTION',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md270',1,'']]],
  ['requirement_20fetcher_20scheduler_20py_23',['CODE SNIPPET: The Requirement Fetcher (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['requirements_24',['REQUIREMENTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md10',1,'2.1 INSTITUTIONAL REQUIREMENTS'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md12',1,'2.3 NON-FUNCTIONAL REQUIREMENTS']]],
  ['requirements_25',['Requirements',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md191',1,'2.5 System Requirements'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md192',1,'Hardware Requirements'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md421',1,'Hardware Requirements'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md193',1,'Software Requirements']]],
  ['requirements_20breakdown_26',['2.2 FUNCTIONAL REQUIREMENTS BREAKDOWN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md11',1,'']]],
  ['requirements_20practicals_20first_27',['2. Sort requirements (Practicals first)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md108',1,'']]],
  ['requirements_20txt_28',['Appendix A: Requirements.txt',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md479',1,'']]],
  ['research_20papers_29',['27.2 Academic and Research Papers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md473',1,'']]],
  ['reserved_30',['[ ALL RIGHTS RESERVED ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md152',1,'']]],
  ['resetting_20the_20database_31',['17.5 Resetting the Database',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md338',1,'']]],
  ['resolution_32',['10.4 BUG LOG AND RESOLUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md93',1,'']]],
  ['resources_33',['Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md474',1,'27.3 Development Tools and Resources'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md475',1,'27.4 Design and UI Resources']]],
  ['response_20time_20optimization_34',['Response Time Optimization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md417',1,'']]],
  ['responsive_20grid_20layouts_35',['7.2 RESPONSIVE GRID LAYOUTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'']]],
  ['responsiveness_36',['Mobile Responsiveness',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md452',1,'']]],
  ['restoring_20from_20backup_37',['16.3 RESTORING FROM BACKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md162',1,'']]],
  ['result_38',['20.8 PDF Export Result',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md369',1,'']]],
  ['result_20table_39',['4.2.6 TABLE: timetable_entry (The Result Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['returns_20false_20and_20informs_20the_20user_40',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['rights_20reserved_41',['[ ALL RIGHTS RESERVED ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md152',1,'']]],
  ['roadmap_42',['25.4 Implementation Roadmap',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md459',1,'']]],
  ['role_20based_20access_20control_43',['Role-Based Access Control',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md431',1,'']]],
  ['role_20based_20access_20control_20rbac_44',['Role Based Access Control RBAC',['../md__r_e_a_d_m_e.html#autotoc_md171',1,'👥 Role-Based Access Control (RBAC)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md282',1,'11. Role-Based Access Control (RBAC)']]],
  ['role_20based_20navigation_3a_45',['Role-based navigation:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md353',1,'']]],
  ['role_20based_20permission_20matrix_46',['K.1 ROLE-BASED PERMISSION MATRIX',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md143',1,'']]],
  ['role_20checks_47',['Level 2 - In-route Role Checks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md287',1,'']]],
  ['role_20definitions_48',['11.2 Role Definitions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md284',1,'']]],
  ['room_49',['Place in Room...',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md113',1,'']]],
  ['room_20for_2010_20classes_50',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['room_20matching_51',['Step 5: ROOM MATCHING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md274',1,'']]],
  ['route_52',['Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md305',1,'13.3 CSV Import Route'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md317',1,'15.3 Compose Message Route'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md258',1,'9.5 Dashboard Route'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md263',1,'9.7 Timetable Generation Route']]],
  ['route_20decorators_53',['Level 1 - Route Decorators',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md286',1,'']]],
  ['route_20definitions_20and_20controllers_20routes_20py_54',['6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['route_20implementation_55',['9.4.1 Login Route Implementation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md257',1,'']]],
  ['route_20role_20checks_56',['Level 2 - In-route Role Checks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md287',1,'']]],
  ['routes_57',['Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md392',1,'22.1 URL Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md256',1,'9.4 Authentication Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md393',1,'Authentication Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md262',1,'Delete Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md261',1,'Edit Routes'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md260',1,'List/Create Routes']]],
  ['routes_20py_58',['routes py',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'9. Routing and Controller Logic (routes.py)']]],
  ['routes_20py_20logic_20excerpts_59',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['routes_20summary_60',['9.6 CRUD Routes Summary',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md259',1,'']]],
  ['routing_20and_20controller_20logic_20routes_20py_61',['9. Routing and Controller Logic (routes.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md252',1,'']]],
  ['row_20db_20object_62',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['rule_63',['5.3 HANDLING PRACTICAL/LAB BLOCKS (3-Hour Rule)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md43',1,'']]],
  ['run_20the_20flask_20development_20server_64',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]]
];
