var searchData=
[
  ['o_20notation_0',['13.3 COMPLEXITY ANALYSIS (Big-O Notation)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md140',1,'']]],
  ['object_1',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['objectives_2',['Objectives',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md196',1,'3.1 Primary Objectives'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md197',1,'3.2 Secondary Objectives']]],
  ['objectives_20of_20the_20study_3',['1.4 OBJECTIVES OF THE STUDY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['objectives_20of_20the_20system_4',['3. Objectives of the System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md195',1,'']]],
  ['occupied_5',['Issue: &quot;Classroom is already occupied&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md375',1,'']]],
  ['of_20app_20py_3a_6',['KEY COMPONENTS OF app.py:',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['of_20contents_7',['Table of Contents',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md181',1,'']]],
  ['of_20scope_8',['4.2 Out of Scope',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md204',1,'']]],
  ['of_20the_20project_9',['4. Scope of the Project',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md200',1,'']]],
  ['of_20the_20study_10',['1.4 OBJECTIVES OF THE STUDY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['of_20the_20system_11',['3. Objectives of the System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md195',1,'']]],
  ['on_20timetable_12',['Issue: Substitution not showing on timetable',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md381',1,'']]],
  ['onboarding_13',['15.2 ADMINISTRATIVE ONBOARDING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md154',1,'']]],
  ['only_201_20room_20for_2010_20classes_14',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['operations_15',['Operations',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md399',1,'Bulk Operations'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md395',1,'CRUD Operations']]],
  ['optimization_16',['OPTIMIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md146',1,'14.1 TOWARDS STOCHASTIC OPTIMIZATION'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md160',1,'16.1 DATABASE OPTIMIZATION']]],
  ['optimization_17',['Optimization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md383',1,'21.2 Performance Optimization'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md384',1,'Database Query Optimization'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md412',1,'Query Optimization'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md417',1,'Response Time Optimization']]],
  ['optional_18',['17.4 Desktop Application Build (Optional)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md337',1,'']]],
  ['options_19',['16.4 Export Options',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md325',1,'']]],
  ['or_20corrupted_20',['Issue: PDF export is blank or corrupted',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md378',1,'']]],
  ['or_20extract_20the_20project_20zip_21',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['or_20password_22',['Issue: &quot;Invalid username or password&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md374',1,'']]],
  ['organization_23',['3.3 BLUEPRINT ORGANIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md17',1,'']]],
  ['out_20of_20scope_24',['4.2 Out of Scope',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md204',1,'']]],
  ['overlaps_25',['K.3 PREVENTING DATABASE OVERLAPS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md145',1,'']]],
  ['overview_26',['4.1 ER DIAGRAM OVERVIEW',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md19',1,'']]],
  ['overview_27',['Overview',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md268',1,'10.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md283',1,'11.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md303',1,'13.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md309',1,'14.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md315',1,'15.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md322',1,'16.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md341',1,'18.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md186',1,'2. Project Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md227',1,'7.1 Database Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md242',1,'8.1 Overview'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md253',1,'9.1 Overview']]]
];
