var searchData=
[
  ['t_20start_0',['Issue: Application won&apos;t start',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md379',1,'']]],
  ['table_1',['Table',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'4.2.5 TABLE: allocation (The Bridge Table)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'4.2.6 TABLE: timetable_entry (The Result Table)'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'A.5 TABLE: TIMETABLE_ENTRY (The Master Table)']]],
  ['table_20definitions_20sqlalchemy_20models_2',['4.2 DETAILED TABLE DEFINITIONS (SQLAlchemy Models)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'']]],
  ['table_20of_20contents_3',['Table of Contents',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md181',1,'']]],
  ['table_3a_20allocation_20the_20bridge_20table_4',['4.2.5 TABLE: allocation (The Bridge Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['table_3a_20classroom_5',['4.2.4 TABLE: classroom',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md28',1,'']]],
  ['table_3a_20classroom_20metadata_6',['A.4 TABLE: CLASSROOM (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md100',1,'']]],
  ['table_3a_20course_7',['4.2.2 TABLE: course',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md24',1,'']]],
  ['table_3a_20course_20metadata_8',['A.2 TABLE: COURSE (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md98',1,'']]],
  ['table_3a_20department_9',['4.2.1 TABLE: department',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md22',1,'']]],
  ['table_3a_20department_20metadata_10',['A.1 TABLE: DEPARTMENT (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md97',1,'']]],
  ['table_3a_20leave_5frequest_11',['4.2.8 TABLE: leave_request',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md36',1,'']]],
  ['table_3a_20message_20mailbox_12',['4.2.10 TABLE: message (Mailbox)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['table_3a_20substitution_13',['4.2.9 TABLE: substitution',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md38',1,'']]],
  ['table_3a_20teacher_14',['4.2.3 TABLE: teacher',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md26',1,'']]],
  ['table_3a_20teacher_20metadata_15',['A.3 TABLE: TEACHER (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md99',1,'']]],
  ['table_3a_20timetable_5fentry_20the_20master_20table_16',['A.5 TABLE: TIMETABLE_ENTRY (The Master Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'']]],
  ['table_3a_20timetable_5fentry_20the_20result_20table_17',['4.2.6 TABLE: timetable_entry (The Result Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['table_3a_20user_20security_20layer_18',['4.2.7 TABLE: user (Security Layer)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['target_20users_19',['2.4 Target Users',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md190',1,'']]],
  ['teacher_20',['7.6 Data Model: Teacher',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md232',1,'']]],
  ['teacher_21',['4.2.3 TABLE: teacher',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md26',1,'']]],
  ['teacher_20availability_3a_22',['Check teacher availability:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md350',1,'']]],
  ['teacher_20dashboard_23',['7.4.2 THE TEACHER DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md75',1,'']]],
  ['teacher_20form_24',['Teacher Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md404',1,'']]],
  ['teacher_20guide_3a_20managing_20your_20academic_20life_25',['9.2 TEACHER GUIDE: MANAGING YOUR ACADEMIC LIFE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md88',1,'']]],
  ['teacher_20links_20are_20also_20cleaned_20up_26',['its courses and teacher links are also cleaned up.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md105',1,'']]],
  ['teacher_20metadata_27',['A.3 TABLE: TEACHER (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md99',1,'']]],
  ['teachers_28',['Sample Teachers',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md484',1,'']]],
  ['teachers_20csv_29',['B. TEACHERS (teachers.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md83',1,'']]],
  ['teachers_20teachers_20csv_30',['B. TEACHERS (teachers.csv)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md83',1,'']]],
  ['technical_20documentation_31',['Full Technical Documentation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md179',1,'']]],
  ['technical_20excellence_32',['Technical Excellence',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md467',1,'']]],
  ['technical_20scope_33',['Technical Scope',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md203',1,'']]],
  ['technical_20stack_34',['🛠️ Technical Stack',['../md__r_e_a_d_m_e.html#autotoc_md174',1,'']]],
  ['technical_20stack_20deep_20dive_20why_20python_20flask_35',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]],
  ['technologies_36',['Technologies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md210',1,'5.1 Backend Technologies'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md211',1,'5.2 Frontend Technologies']]],
  ['technology_20stack_37',['5. Technology Stack',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md209',1,'']]],
  ['template_20level_20visibility_38',['Level 3 - Template-Level Visibility',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md288',1,'']]],
  ['template_20rendering_20examples_39',['19.2 Template Rendering Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md351',1,'']]],
  ['templates_20base_20html_40',['J.1 THE MASTER LAYOUT (templates/base.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md141',1,'']]],
  ['templates_20timetable_20html_41',['J.2 THE TIMETABLE GRID (templates/timetable.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md142',1,'']]],
  ['term_20enhancements_20v1_201_42',['25.1 Short-Term Enhancements (v1.1)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md445',1,'']]],
  ['term_20enhancements_20v2_200_43',['25.2 Medium-Term Enhancements (v2.0)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md449',1,'']]],
  ['term_20vision_20v3_200_44',['25.3 Long-Term Vision (v3.0)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md454',1,'']]],
  ['test_20scenarios_45',['18.4 Test Scenarios',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md344',1,'']]],
  ['testing_46',['10.3 SECURITY PENETRATION TESTING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md92',1,'']]],
  ['testing_47',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['testing_20and_20validation_48',['18. Testing and Validation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md340',1,'']]],
  ['testing_20strategy_49',['10.1 TESTING STRATEGY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md90',1,'']]],
  ['testing_20uat_50',['10.2 USER ACCEPTANCE TESTING (UAT)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md91',1,'']]],
  ['tests_51',['TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md120',1,'C.1 AUTHENTICATION TESTS'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md121',1,'C.2 DATABASE INTEGRITY TESTS'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md122',1,'C.3 SCHEDULER STRESS TESTS'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md123',1,'C.4 USER INTERFACE (UI) TESTS']]],
  ['that_20if_20a_20department_20is_20removed_52',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['the_20admin_20dashboard_53',['7.4.1 THE ADMIN DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md73',1,'']]],
  ['the_20algorithm_20returns_20false_20and_20informs_20the_20user_54',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['the_20application_55',['STEP 5: Access the application',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md334',1,'']]],
  ['the_20bridge_20table_56',['4.2.5 TABLE: allocation (The Bridge Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md30',1,'']]],
  ['the_20bulk_20input_20parsing_20logic_57',['8.1 THE BULK INPUT PARSING LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['the_20constraint_20satisfaction_20problem_20csp_58',['5.1 THE CONSTRAINT-SATISFACTION PROBLEM (CSP)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md41',1,'']]],
  ['the_20constraint_20satisfaction_20problem_20csp_20model_59',['13.1 THE CONSTRAINT SATISFACTION PROBLEM (CSP) MODEL',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md138',1,'']]],
  ['the_20controller_20routes_20py_20logic_20excerpts_60',['B.3 THE CONTROLLER (routes.py - Logic Excerpts)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md115',1,'']]],
  ['the_20core_20problem_20statement_61',['1.2 THE CORE PROBLEM STATEMENT',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md6',1,'']]],
  ['the_20database_62',['17.5 Resetting the Database',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md338',1,'']]],
  ['the_20decorator_63',['K.2 THE @admin_required DECORATOR',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md144',1,'']]],
  ['the_20design_20tokens_20index_20css_64',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['the_20executable_65',['11.2 DESKTOP DEPLOYMENT (THE EXECUTABLE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md95',1,'']]],
  ['the_20flask_20development_20server_66',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]],
  ['the_20heuristic_20search_20space_67',['13.2 THE HEURISTIC SEARCH SPACE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md139',1,'']]],
  ['the_20intelligent_20approach_68',['1.3 PROPOSED SOLUTION: THE INTELLIGENT APPROACH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md7',1,'']]],
  ['the_20journey_20ahead_69',['14.3 THE JOURNEY AHEAD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md148',1,'']]],
  ['the_20login_20experience_70',['15.1 THE LOGIN EXPERIENCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md153',1,'']]],
  ['the_20master_20layout_20templates_20base_20html_71',['J.1 THE MASTER LAYOUT (templates/base.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md141',1,'']]],
  ['the_20master_20table_72',['A.5 TABLE: TIMETABLE_ENTRY (The Master Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'']]],
  ['the_20model_20view_20controller_20mvc_20pattern_73',['3.2 THE MODEL-VIEW-CONTROLLER (MVC) PATTERN',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md16',1,'']]],
  ['the_20project_74',['4. Scope of the Project',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md200',1,'']]],
  ['the_20project_20zip_75',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['the_20repository_20or_20extract_20the_20project_20zip_76',['STEP 1: Clone the repository or extract the project ZIP',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md330',1,'']]],
  ['the_20requirement_20fetcher_20scheduler_20py_77',['CODE SNIPPET: The Requirement Fetcher (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['the_20result_20table_78',['4.2.6 TABLE: timetable_entry (The Result Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['the_20scheduling_20algorithm_20scheduler_20py_79',['B.2 THE SCHEDULING ALGORITHM (scheduler.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md106',1,'']]],
  ['the_20scheduling_20controls_80',['6.2.3 THE SCHEDULING CONTROLS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['the_20search_20space_20is_20too_20small_20e_20g_20only_201_20room_20for_2010_20classes_81',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['the_20student_20dashboard_82',['7.4.3 THE STUDENT DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md77',1,'']]],
  ['the_20study_83',['1.4 OBJECTIVES OF THE STUDY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md8',1,'']]],
  ['the_20system_84',['3. Objectives of the System',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md195',1,'']]],
  ['the_20teacher_20dashboard_85',['7.4.2 THE TEACHER DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md75',1,'']]],
  ['the_20timetable_86',['15.4 GENERATING THE TIMETABLE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md158',1,'']]],
  ['the_20timetable_20grid_20templates_20timetable_20html_87',['J.2 THE TIMETABLE GRID (templates/timetable.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md142',1,'']]],
  ['the_20user_88',['the algorithm returns False and informs the user.',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md117',1,'']]],
  ['theory_20sessions_201_20hour_20slots_89',['Logic for Theory sessions (1-hour slots)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['this_20stack_90',['5.4 Why This Stack?',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md213',1,'']]],
  ['time_20optimization_91',['Response Time Optimization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md417',1,'']]],
  ['timetable_92',['15.4 GENERATING THE TIMETABLE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md158',1,'']]],
  ['timetable_93',['timetable',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md373',1,'Issue: &quot;Failed to generate timetable&quot;'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md381',1,'Issue: Substitution not showing on timetable']]],
  ['timetable_20cell_3a_94',['Display timetable cell:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md352',1,'']]],
  ['timetable_20display_20logic_95',['6.2.4 TIMETABLE DISPLAY LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md62',1,'']]],
  ['timetable_20entry_96',['20.4 Edit Timetable Entry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md365',1,'']]],
  ['timetable_20entry_20edit_5ftimetable_5fentry_20html_97',['EDIT TIMETABLE ENTRY (edit_timetable_entry.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md298',1,'']]],
  ['timetable_20entry_20form_98',['Timetable Entry Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md407',1,'']]],
  ['timetable_20for_20today_3a_99',['Get timetable for today:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md349',1,'']]],
  ['timetable_20generation_20route_100',['9.7 Timetable Generation Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md263',1,'']]],
  ['timetable_20grid_20mockup_101',['F.3 TIMETABLE GRID MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md131',1,'']]],
  ['timetable_20grid_20structure_102',['12.4 Timetable Grid Structure',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md299',1,'']]],
  ['timetable_20grid_20templates_20timetable_20html_103',['J.2 THE TIMETABLE GRID (templates/timetable.html)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md142',1,'']]],
  ['timetable_20html_104',['timetable html',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md142',1,'J.2 THE TIMETABLE GRID (templates/timetable.html)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md297',1,'TIMETABLE PAGE (timetable.html)']]],
  ['timetable_20management_105',['Timetable Management',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md396',1,'']]],
  ['timetable_20management_20system_106',['Timetable Management System',['../md__r_e_a_d_m_e.html',1,'Intelligent Timetable Management System'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html',1,'Intelligent Timetable Management System']]],
  ['timetable_20page_20timetable_20html_107',['TIMETABLE PAGE (timetable.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md297',1,'']]],
  ['timetable_20view_108',['20.3 Timetable View',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md364',1,'']]],
  ['timetable_5fentry_20the_20master_20table_109',['A.5 TABLE: TIMETABLE_ENTRY (The Master Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md101',1,'']]],
  ['timetable_5fentry_20the_20result_20table_110',['4.2.6 TABLE: timetable_entry (The Result Table)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md32',1,'']]],
  ['timetableentry_111',['7.9 Data Model: TimetableEntry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md235',1,'']]],
  ['to_20generate_20timetable_112',['Issue: &quot;Failed to generate timetable&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md373',1,'']]],
  ['to_20map_20row_20db_20object_113',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['today_3a_114',['Get timetable for today:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md349',1,'']]],
  ['tokens_115',['7.1 GLASSMORPHISM DESIGN TOKENS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'']]],
  ['tokens_20index_20css_116',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['too_20small_20e_20g_20only_201_20room_20for_2010_20classes_117',['If the search space is too small (e.g., only 1 room for 10 classes)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md116',1,'']]],
  ['tools_118',['5.3 Development Tools',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md212',1,'']]],
  ['tools_20and_20resources_119',['27.3 Development Tools and Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md474',1,'']]],
  ['towards_20stochastic_20optimization_120',['14.1 TOWARDS STOCHASTIC OPTIMIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md146',1,'']]],
  ['transactional_20block_121',['Transactional Block',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md118',1,'']]],
  ['troubleshooting_20guide_122',['21. Troubleshooting Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md371',1,'']]],
  ['tuning_123',['15.5 MANUAL EDITS AND FINE-TUNING',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md159',1,'']]],
  ['txt_124',['Appendix A: Requirements.txt',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md479',1,'']]],
  ['types_125',['13.2 Supported Import Types',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md304',1,'']]]
];
