var searchData=
[
  ['d_3a_20sample_20data_20for_20testing_0',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['dashboard_1',['DASHBOARD',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md73',1,'7.4.1 THE ADMIN DASHBOARD'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md75',1,'7.4.2 THE TEACHER DASHBOARD'],['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md77',1,'7.4.3 THE STUDENT DASHBOARD']]],
  ['dashboard_2',['20.2 Dashboard',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md363',1,'']]],
  ['dashboard_20and_20main_20views_3',['Dashboard and Main Views',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md394',1,'']]],
  ['dashboard_20dashboard_20html_4',['DASHBOARD (dashboard.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md296',1,'']]],
  ['dashboard_20html_5',['DASHBOARD (dashboard.html)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md296',1,'']]],
  ['dashboard_20mockup_6',['F.2 ADMIN DASHBOARD MOCKUP',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md129',1,'']]],
  ['dashboard_20route_7',['9.5 Dashboard Route',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md258',1,'']]],
  ['dashboards_8',['7.4 USER PERSONA DASHBOARDS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md71',1,'']]],
  ['data_20administration_20crud_9',['6.2.2 DATA ADMINISTRATION (CRUD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'']]],
  ['data_20ethics_10',['18.1 INSTITUTIONAL DATA ETHICS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md165',1,'']]],
  ['data_20flow_20diagrams_20dfd_11',['3.4 DATA FLOW DIAGRAMS (DFD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'']]],
  ['data_20flow_20example_12',['Data Flow Example',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md224',1,'']]],
  ['data_20for_20testing_13',['Appendix D: Sample Data for Testing',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md482',1,'']]],
  ['data_20management_14',['📊 Data Management',['../md__r_e_a_d_m_e.html#autotoc_md173',1,'']]],
  ['data_20model_3a_20allocation_15',['7.8 Data Model: Allocation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md234',1,'']]],
  ['data_20model_3a_20classroom_16',['7.7 Data Model: Classroom',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md233',1,'']]],
  ['data_20model_3a_20course_17',['7.5 Data Model: Course',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md231',1,'']]],
  ['data_20model_3a_20department_18',['7.4 Data Model: Department',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md230',1,'']]],
  ['data_20model_3a_20leaverequest_19',['7.11 Data Model: LeaveRequest',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md237',1,'']]],
  ['data_20model_3a_20message_20',['7.13 Data Model: Message',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md239',1,'']]],
  ['data_20model_3a_20substitution_21',['7.12 Data Model: Substitution',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md238',1,'']]],
  ['data_20model_3a_20teacher_22',['7.6 Data Model: Teacher',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md232',1,'']]],
  ['data_20model_3a_20timetableentry_23',['7.9 Data Model: TimetableEntry',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md235',1,'']]],
  ['data_20model_3a_20user_24',['7.10 Data Model: User',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md236',1,'']]],
  ['data_20models_25',['7. Database Design and Data Models',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md226',1,'']]],
  ['data_20parameters_26',['22.3 Form Data Parameters',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md401',1,'']]],
  ['data_20privacy_20gdpr_20compliance_27',['18.2 DATA PRIVACY &amp;amp; GDPR COMPLIANCE',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md166',1,'']]],
  ['data_20security_28',['24.3 Data Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md433',1,'']]],
  ['data_20upload_20csv_29',['15.3.3 BULK DATA UPLOAD (CSV)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md157',1,'']]],
  ['data_20volume_20limits_30',['Data Volume Limits',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md419',1,'']]],
  ['database_31',['17.5 Resetting the Database',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md338',1,'']]],
  ['database_20backup_32',['Database Backup',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md388',1,'']]],
  ['database_20backup_20policy_33',['G.2 DATABASE BACKUP POLICY',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md133',1,'']]],
  ['database_20commit_34',['Step 7: DATABASE COMMIT',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md276',1,'']]],
  ['database_20design_20and_20data_20models_35',['7. Database Design and Data Models',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md226',1,'']]],
  ['database_20initialization_36',['8.3.6 Database Initialization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md250',1,'']]],
  ['database_20integrity_20tests_37',['C.2 DATABASE INTEGRITY TESTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md121',1,'']]],
  ['database_20locked_20errors_38',['Issue: Database locked errors',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md380',1,'']]],
  ['database_20migration_39',['Database Migration',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md450',1,'']]],
  ['database_20optimization_40',['16.1 DATABASE OPTIMIZATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md160',1,'']]],
  ['database_20overlaps_41',['K.3 PREVENTING DATABASE OVERLAPS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md145',1,'']]],
  ['database_20overview_42',['7.1 Database Overview',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md227',1,'']]],
  ['database_20performance_43',['23.1 Database Performance',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md410',1,'']]],
  ['database_20query_20examples_44',['19.1 Database Query Examples',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md347',1,'']]],
  ['database_20query_20logging_45',['Database Query Logging',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md424',1,'']]],
  ['database_20query_20optimization_46',['Database Query Optimization',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md384',1,'']]],
  ['database_20schema_20sql_47',['Appendix B: Database Schema SQL',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md480',1,'']]],
  ['database_20security_48',['Database Security',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md434',1,'']]],
  ['date_3a_20march_202026_49',['DATE: MARCH 2026',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md150',1,'']]],
  ['db_20object_50',['Logic to map row -&amp;gt; DB Object',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md119',1,'']]],
  ['declaration_51',['0.1 DECLARATION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md2',1,'']]],
  ['decorator_52',['K.2 THE @admin_required DECORATOR',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md144',1,'']]],
  ['decorator_53',['9.3 Admin Guard Decorator',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md255',1,'']]],
  ['decorators_54',['Level 1 - Route Decorators',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md286',1,'']]],
  ['deep_20dive_20why_20python_20flask_55',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]],
  ['definition_56',['9.2 Blueprint Definition',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md254',1,'']]],
  ['definitions_57',['11.2 Role Definitions',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md284',1,'']]],
  ['definitions_20and_20controllers_20routes_20py_58',['6.2 ROUTE DEFINITIONS AND CONTROLLERS (routes.py)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['definitions_20sqlalchemy_20models_59',['4.2 DETAILED TABLE DEFINITIONS (SQLAlchemy Models)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'']]],
  ['delete_20routes_60',['Delete Routes',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md262',1,'']]],
  ['deletes_20ensure_20that_20if_20a_20department_20is_20removed_61',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['density_20checker_20check_5fdensity_20py_62',['18.2 Schedule Density Checker (check_density.py)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md342',1,'']]],
  ['department_63',['7.4 Data Model: Department',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md230',1,'']]],
  ['department_64',['4.2.1 TABLE: department',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md22',1,'']]],
  ['department_20batch_20limit_20reached_65',['Issue: &quot;Department batch limit reached&quot;',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md376',1,'']]],
  ['department_20form_66',['Department Form',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md403',1,'']]],
  ['department_20is_20removed_67',['Cascade deletes ensure that if a department is removed,',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md104',1,'']]],
  ['department_20metadata_68',['A.1 TABLE: DEPARTMENT (Metadata)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md97',1,'']]],
  ['department_3a_69',['Find all courses for a department:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md348',1,'']]],
  ['departments_70',['15.2.1 MANAGING DEPARTMENTS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md155',1,'']]],
  ['departments_71',['Sample Departments',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md483',1,'']]],
  ['dependencies_72',['STEP 3: Install all Python dependencies',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md332',1,'']]],
  ['deployment_20guide_73',['17. Installation and Deployment Guide',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md327',1,'']]],
  ['deployment_20heroku_20aws_20azure_74',['11.1 CLOUD DEPLOYMENT (HEROKU / AWS / AZURE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md94',1,'']]],
  ['deployment_20the_20executable_75',['11.2 DESKTOP DEPLOYMENT (THE EXECUTABLE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md95',1,'']]],
  ['descending_76',['Priority Hack: Sort by duration descending',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md110',1,'']]],
  ['description_77',['2.2 Project Description',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md188',1,'']]],
  ['design_78',['Design',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md269',1,'10.2 Scheduling Algorithm Design'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md291',1,'12. User Interface and Frontend Design']]],
  ['design_20and_20data_20models_79',['7. Database Design and Data Models',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md226',1,'']]],
  ['design_20and_20ui_20resources_80',['27.4 Design and UI Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md475',1,'']]],
  ['design_20philosophy_81',['12.1 Design Philosophy',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md292',1,'']]],
  ['design_20tokens_82',['7.1 GLASSMORPHISM DESIGN TOKENS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'']]],
  ['design_20tokens_20index_20css_83',['E.1 THE DESIGN TOKENS (index.css)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md124',1,'']]],
  ['desktop_20application_20build_20optional_84',['17.4 Desktop Application Build (Optional)',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md337',1,'']]],
  ['desktop_20deployment_20the_20executable_85',['11.2 DESKTOP DEPLOYMENT (THE EXECUTABLE)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md95',1,'']]],
  ['desktop_20vs_20development_20mode_86',['8.3.1 Desktop vs. Development Mode',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md245',1,'']]],
  ['detailed_20csv_20specifications_87',['8.2 DETAILED CSV SPECIFICATIONS',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md79',1,'']]],
  ['detailed_20table_20definitions_20sqlalchemy_20models_88',['4.2 DETAILED TABLE DEFINITIONS (SQLAlchemy Models)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md20',1,'']]],
  ['detection_20algorithm_20walkthrough_89',['5.5 CONFLICT DETECTION ALGORITHM WALKTHROUGH',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['detection_20function_90',['9.8 Conflict Detection Function',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md264',1,'']]],
  ['development_91',['API Development',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md451',1,'']]],
  ['development_20mode_92',['Development Mode',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md329',1,'17.2 Installation Steps (Web / Development Mode)'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md245',1,'8.3.1 Desktop vs. Development Mode']]],
  ['development_20server_93',['STEP 4: Run the Flask development server',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md333',1,'']]],
  ['development_20tools_94',['5.3 Development Tools',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md212',1,'']]],
  ['development_20tools_20and_20resources_95',['27.3 Development Tools and Resources',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md474',1,'']]],
  ['dfd_96',['3.4 DATA FLOW DIAGRAMS (DFD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'']]],
  ['diagram_97',['Diagram',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md220',1,'6.2 Architecture Diagram'],['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md228',1,'7.2 Entity Relationship Diagram']]],
  ['diagram_20overview_98',['4.1 ER DIAGRAM OVERVIEW',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md19',1,'']]],
  ['diagrams_20dfd_99',['3.4 DATA FLOW DIAGRAMS (DFD)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md18',1,'']]],
  ['display_20logic_100',['6.2.4 TIMETABLE DISPLAY LOGIC',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md62',1,'']]],
  ['display_20logic_101',['14.4 Substitution Display Logic',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md312',1,'']]],
  ['display_20timetable_20cell_3a_102',['Display timetable cell:',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md352',1,'']]],
  ['distribution_103',['H.2 FAIR WORKLOAD DISTRIBUTION',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md136',1,'']]],
  ['dive_20why_20python_20flask_104',['2.5 TECHNICAL STACK DEEP DIVE (WHY PYTHON/FLASK?)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md14',1,'']]],
  ['documentation_105',['Full Technical Documentation',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md179',1,'']]],
  ['documentation_20and_20frameworks_106',['27.1 Documentation and Frameworks',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md472',1,'']]],
  ['documentation_20release_107',['[ FINAL DOCUMENTATION RELEASE ]',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md164',1,'']]],
  ['domain_20building_108',['Step 3: DOMAIN BUILDING',['../md__t_i_m_e_t_a_b_l_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md272',1,'']]],
  ['domain_20prevents_20repetitive_20schedules_109',['Randomized &apos;Domain&apos; prevents repetitive schedules',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md111',1,'']]],
  ['duration_20descending_110',['Priority Hack: Sort by duration descending',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md110',1,'']]],
  ['dynamic_20canvas_20animations_20background_20engine_111',['7.3 DYNAMIC CANVAS ANIMATIONS (Background Engine)',['../md__p_r_e_m_i_u_m___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]]
];
